template: native
provider: runpod
organization: runpod
major-version: 0
providerDefaultBranch: main
publishRegistry: true
providerVersion: github.com/runpod/pulumi-runpod/provider.Version
parallel: 3
sdkModuleDir: sdk/go/runpod
languages:
    - nodejs
    - python
    - go
    - dotnet
publish:
    cdn: false
github-app:
    enabled: false
