// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Runpod
{
    [RunpodResourceType("runpod:index:ContainerRegistryAuth")]
    public partial class ContainerRegistryAuth : global::Pulumi.CustomResource
    {
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("password")]
        public Output<string> Password { get; private set; } = null!;

        [Output("registryAuthId")]
        public Output<string> RegistryAuthId { get; private set; } = null!;

        [Output("username")]
        public Output<string> Username { get; private set; } = null!;


        /// <summary>
        /// Create a ContainerRegistryAuth resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ContainerRegistryAuth(string name, ContainerRegistryAuthArgs args, CustomResourceOptions? options = null)
            : base("runpod:index:ContainerRegistryAuth", name, args ?? new ContainerRegistryAuthArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ContainerRegistryAuth(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("runpod:index:ContainerRegistryAuth", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/runpod/pulumi-runpod",
                AdditionalSecretOutputs =
                {
                    "password",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ContainerRegistryAuth resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ContainerRegistryAuth Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new ContainerRegistryAuth(name, id, options);
        }
    }

    public sealed class ContainerRegistryAuthArgs : global::Pulumi.ResourceArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("password", required: true)]
        private Input<string>? _password;
        public Input<string>? Password
        {
            get => _password;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _password = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("username", required: true)]
        public Input<string> Username { get; set; } = null!;

        public ContainerRegistryAuthArgs()
        {
        }
        public static new ContainerRegistryAuthArgs Empty => new ContainerRegistryAuthArgs();
    }
}
