// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Runpod
{
    public static class GetDataCenters
    {
        public static Task<GetDataCentersResult> InvokeAsync(GetDataCentersArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetDataCentersResult>("runpod:index:getDataCenters", args ?? new GetDataCentersArgs(), options.WithDefaults());

        public static Output<GetDataCentersResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetDataCentersResult>("runpod:index:getDataCenters", InvokeArgs.Empty, options.WithDefaults());

        public static Output<GetDataCentersResult> Invoke(InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetDataCentersResult>("runpod:index:getDataCenters", InvokeArgs.Empty, options.WithDefaults());
    }


    public sealed class GetDataCentersArgs : global::Pulumi.InvokeArgs
    {
        public GetDataCentersArgs()
        {
        }
        public static new GetDataCentersArgs Empty => new GetDataCentersArgs();
    }


    [OutputType]
    public sealed class GetDataCentersResult
    {
        /// <summary>
        /// The list of available RunPod data centers.
        /// </summary>
        public readonly ImmutableArray<Outputs.DataCenterOutput> DataCenters;

        [OutputConstructor]
        private GetDataCentersResult(ImmutableArray<Outputs.DataCenterOutput> dataCenters)
        {
            DataCenters = dataCenters;
        }
    }
}
