// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Runpod
{
    [RunpodResourceType("runpod:index:NetworkVolume")]
    public partial class NetworkVolume : global::Pulumi.CustomResource
    {
        [Output("dataCenterId")]
        public Output<string> DataCenterId { get; private set; } = null!;

        [Output("isNextGenStorage")]
        public Output<bool?> IsNextGenStorage { get; private set; } = null!;

        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("networkVolumeId")]
        public Output<string> NetworkVolumeId { get; private set; } = null!;

        [Output("size")]
        public Output<int> Size { get; private set; } = null!;


        /// <summary>
        /// Create a NetworkVolume resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public NetworkVolume(string name, NetworkVolumeArgs args, CustomResourceOptions? options = null)
            : base("runpod:index:NetworkVolume", name, args ?? new NetworkVolumeArgs(), MakeResourceOptions(options, ""))
        {
        }

        private NetworkVolume(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("runpod:index:NetworkVolume", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/runpod/pulumi-runpod",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing NetworkVolume resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static NetworkVolume Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new NetworkVolume(name, id, options);
        }
    }

    public sealed class NetworkVolumeArgs : global::Pulumi.ResourceArgs
    {
        [Input("dataCenterId", required: true)]
        public Input<string> DataCenterId { get; set; } = null!;

        [Input("isNextGenStorage")]
        public Input<bool>? IsNextGenStorage { get; set; }

        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("size", required: true)]
        public Input<int> Size { get; set; } = null!;

        public NetworkVolumeArgs()
        {
        }
        public static new NetworkVolumeArgs Empty => new NetworkVolumeArgs();
    }
}
