# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

import types

__config__ = pulumi.Config('runpod')


class _ExportableConfig(types.ModuleType):
    @property
    def api_key(self) -> Optional[str]:
        """
        The RunPod API key for authentication. Can also be set via the RUNPOD_API_KEY environment variable.
        """
        return __config__.get('apiKey') or _utilities.get_env('RUNPOD_API_KEY')

    @property
    def api_url(self) -> Optional[str]:
        """
        The RunPod API URL. Defaults to https://api.runpod.io/graphql. Can also be set via the RUNPOD_API_URL environment variable.
        """
        return __config__.get('apiUrl') or _utilities.get_env('RUNPOD_API_URL')

