// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package runpod

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/runpod/pulumi-runpod/sdk/go/runpod/internal"
)

type ContainerRegistryAuth struct {
	pulumi.CustomResourceState

	// A name for the registry auth credentials.
	Name pulumi.StringOutput `pulumi:"name"`
	// The password or access token for the container registry.
	Password pulumi.StringOutput `pulumi:"password"`
	// The unique identifier of the registry auth.
	RegistryAuthId pulumi.StringOutput `pulumi:"registryAuthId"`
	// The username for the container registry.
	Username pulumi.StringOutput `pulumi:"username"`
}

// NewContainerRegistryAuth registers a new resource with the given unique name, arguments, and options.
func NewContainerRegistryAuth(ctx *pulumi.Context,
	name string, args *ContainerRegistryAuthArgs, opts ...pulumi.ResourceOption) (*ContainerRegistryAuth, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.Password == nil {
		return nil, errors.New("invalid value for required argument 'Password'")
	}
	if args.Username == nil {
		return nil, errors.New("invalid value for required argument 'Username'")
	}
	if args.Password != nil {
		args.Password = pulumi.ToSecret(args.Password).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"password",
	})
	opts = append(opts, secrets)
	replaceOnChanges := pulumi.ReplaceOnChanges([]string{
		"name",
	})
	opts = append(opts, replaceOnChanges)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ContainerRegistryAuth
	err := ctx.RegisterResource("runpod:index:ContainerRegistryAuth", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetContainerRegistryAuth gets an existing ContainerRegistryAuth resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetContainerRegistryAuth(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ContainerRegistryAuthState, opts ...pulumi.ResourceOption) (*ContainerRegistryAuth, error) {
	var resource ContainerRegistryAuth
	err := ctx.ReadResource("runpod:index:ContainerRegistryAuth", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ContainerRegistryAuth resources.
type containerRegistryAuthState struct {
}

type ContainerRegistryAuthState struct {
}

func (ContainerRegistryAuthState) ElementType() reflect.Type {
	return reflect.TypeOf((*containerRegistryAuthState)(nil)).Elem()
}

type containerRegistryAuthArgs struct {
	// A name for the registry auth credentials.
	Name string `pulumi:"name"`
	// The password or access token for the container registry.
	Password string `pulumi:"password"`
	// The username for the container registry.
	Username string `pulumi:"username"`
}

// The set of arguments for constructing a ContainerRegistryAuth resource.
type ContainerRegistryAuthArgs struct {
	// A name for the registry auth credentials.
	Name pulumi.StringInput
	// The password or access token for the container registry.
	Password pulumi.StringInput
	// The username for the container registry.
	Username pulumi.StringInput
}

func (ContainerRegistryAuthArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*containerRegistryAuthArgs)(nil)).Elem()
}

type ContainerRegistryAuthInput interface {
	pulumi.Input

	ToContainerRegistryAuthOutput() ContainerRegistryAuthOutput
	ToContainerRegistryAuthOutputWithContext(ctx context.Context) ContainerRegistryAuthOutput
}

func (*ContainerRegistryAuth) ElementType() reflect.Type {
	return reflect.TypeOf((**ContainerRegistryAuth)(nil)).Elem()
}

func (i *ContainerRegistryAuth) ToContainerRegistryAuthOutput() ContainerRegistryAuthOutput {
	return i.ToContainerRegistryAuthOutputWithContext(context.Background())
}

func (i *ContainerRegistryAuth) ToContainerRegistryAuthOutputWithContext(ctx context.Context) ContainerRegistryAuthOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ContainerRegistryAuthOutput)
}

// ContainerRegistryAuthArrayInput is an input type that accepts ContainerRegistryAuthArray and ContainerRegistryAuthArrayOutput values.
// You can construct a concrete instance of `ContainerRegistryAuthArrayInput` via:
//
//	ContainerRegistryAuthArray{ ContainerRegistryAuthArgs{...} }
type ContainerRegistryAuthArrayInput interface {
	pulumi.Input

	ToContainerRegistryAuthArrayOutput() ContainerRegistryAuthArrayOutput
	ToContainerRegistryAuthArrayOutputWithContext(context.Context) ContainerRegistryAuthArrayOutput
}

type ContainerRegistryAuthArray []ContainerRegistryAuthInput

func (ContainerRegistryAuthArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ContainerRegistryAuth)(nil)).Elem()
}

func (i ContainerRegistryAuthArray) ToContainerRegistryAuthArrayOutput() ContainerRegistryAuthArrayOutput {
	return i.ToContainerRegistryAuthArrayOutputWithContext(context.Background())
}

func (i ContainerRegistryAuthArray) ToContainerRegistryAuthArrayOutputWithContext(ctx context.Context) ContainerRegistryAuthArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ContainerRegistryAuthArrayOutput)
}

// ContainerRegistryAuthMapInput is an input type that accepts ContainerRegistryAuthMap and ContainerRegistryAuthMapOutput values.
// You can construct a concrete instance of `ContainerRegistryAuthMapInput` via:
//
//	ContainerRegistryAuthMap{ "key": ContainerRegistryAuthArgs{...} }
type ContainerRegistryAuthMapInput interface {
	pulumi.Input

	ToContainerRegistryAuthMapOutput() ContainerRegistryAuthMapOutput
	ToContainerRegistryAuthMapOutputWithContext(context.Context) ContainerRegistryAuthMapOutput
}

type ContainerRegistryAuthMap map[string]ContainerRegistryAuthInput

func (ContainerRegistryAuthMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ContainerRegistryAuth)(nil)).Elem()
}

func (i ContainerRegistryAuthMap) ToContainerRegistryAuthMapOutput() ContainerRegistryAuthMapOutput {
	return i.ToContainerRegistryAuthMapOutputWithContext(context.Background())
}

func (i ContainerRegistryAuthMap) ToContainerRegistryAuthMapOutputWithContext(ctx context.Context) ContainerRegistryAuthMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ContainerRegistryAuthMapOutput)
}

type ContainerRegistryAuthOutput struct{ *pulumi.OutputState }

func (ContainerRegistryAuthOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ContainerRegistryAuth)(nil)).Elem()
}

func (o ContainerRegistryAuthOutput) ToContainerRegistryAuthOutput() ContainerRegistryAuthOutput {
	return o
}

func (o ContainerRegistryAuthOutput) ToContainerRegistryAuthOutputWithContext(ctx context.Context) ContainerRegistryAuthOutput {
	return o
}

// A name for the registry auth credentials.
func (o ContainerRegistryAuthOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *ContainerRegistryAuth) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The password or access token for the container registry.
func (o ContainerRegistryAuthOutput) Password() pulumi.StringOutput {
	return o.ApplyT(func(v *ContainerRegistryAuth) pulumi.StringOutput { return v.Password }).(pulumi.StringOutput)
}

// The unique identifier of the registry auth.
func (o ContainerRegistryAuthOutput) RegistryAuthId() pulumi.StringOutput {
	return o.ApplyT(func(v *ContainerRegistryAuth) pulumi.StringOutput { return v.RegistryAuthId }).(pulumi.StringOutput)
}

// The username for the container registry.
func (o ContainerRegistryAuthOutput) Username() pulumi.StringOutput {
	return o.ApplyT(func(v *ContainerRegistryAuth) pulumi.StringOutput { return v.Username }).(pulumi.StringOutput)
}

type ContainerRegistryAuthArrayOutput struct{ *pulumi.OutputState }

func (ContainerRegistryAuthArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ContainerRegistryAuth)(nil)).Elem()
}

func (o ContainerRegistryAuthArrayOutput) ToContainerRegistryAuthArrayOutput() ContainerRegistryAuthArrayOutput {
	return o
}

func (o ContainerRegistryAuthArrayOutput) ToContainerRegistryAuthArrayOutputWithContext(ctx context.Context) ContainerRegistryAuthArrayOutput {
	return o
}

func (o ContainerRegistryAuthArrayOutput) Index(i pulumi.IntInput) ContainerRegistryAuthOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ContainerRegistryAuth {
		return vs[0].([]*ContainerRegistryAuth)[vs[1].(int)]
	}).(ContainerRegistryAuthOutput)
}

type ContainerRegistryAuthMapOutput struct{ *pulumi.OutputState }

func (ContainerRegistryAuthMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ContainerRegistryAuth)(nil)).Elem()
}

func (o ContainerRegistryAuthMapOutput) ToContainerRegistryAuthMapOutput() ContainerRegistryAuthMapOutput {
	return o
}

func (o ContainerRegistryAuthMapOutput) ToContainerRegistryAuthMapOutputWithContext(ctx context.Context) ContainerRegistryAuthMapOutput {
	return o
}

func (o ContainerRegistryAuthMapOutput) MapIndex(k pulumi.StringInput) ContainerRegistryAuthOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ContainerRegistryAuth {
		return vs[0].(map[string]*ContainerRegistryAuth)[vs[1].(string)]
	}).(ContainerRegistryAuthOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ContainerRegistryAuthInput)(nil)).Elem(), &ContainerRegistryAuth{})
	pulumi.RegisterInputType(reflect.TypeOf((*ContainerRegistryAuthArrayInput)(nil)).Elem(), ContainerRegistryAuthArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ContainerRegistryAuthMapInput)(nil)).Elem(), ContainerRegistryAuthMap{})
	pulumi.RegisterOutputType(ContainerRegistryAuthOutput{})
	pulumi.RegisterOutputType(ContainerRegistryAuthArrayOutput{})
	pulumi.RegisterOutputType(ContainerRegistryAuthMapOutput{})
}
