// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package runpod

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/runpod/pulumi-runpod/sdk/go/runpod/internal"
)

type Endpoint struct {
	pulumi.CustomResourceState

	AllowedCudaVersions pulumi.StringPtrOutput   `pulumi:"allowedCudaVersions"`
	BindEndpoint        pulumi.BoolPtrOutput     `pulumi:"bindEndpoint"`
	EndpointId          pulumi.StringOutput      `pulumi:"endpointId"`
	Env                 pulumi.StringMapOutput   `pulumi:"env"`
	ExecutionTimeoutMs  pulumi.IntPtrOutput      `pulumi:"executionTimeoutMs"`
	FlashBootType       pulumi.StringPtrOutput   `pulumi:"flashBootType"`
	FlashEnvironmentId  pulumi.StringPtrOutput   `pulumi:"flashEnvironmentId"`
	GpuCount            pulumi.IntPtrOutput      `pulumi:"gpuCount"`
	GpuIds              pulumi.StringPtrOutput   `pulumi:"gpuIds"`
	HubReleaseId        pulumi.StringPtrOutput   `pulumi:"hubReleaseId"`
	IdleTimeout         pulumi.IntPtrOutput      `pulumi:"idleTimeout"`
	InstanceIds         pulumi.StringArrayOutput `pulumi:"instanceIds"`
	Locations           pulumi.StringPtrOutput   `pulumi:"locations"`
	MinCudaVersion      pulumi.StringPtrOutput   `pulumi:"minCudaVersion"`
	ModelName           pulumi.StringPtrOutput   `pulumi:"modelName"`
	ModelReferences     pulumi.StringArrayOutput `pulumi:"modelReferences"`
	Name                pulumi.StringOutput      `pulumi:"name"`
	NetworkVolumeId     pulumi.StringPtrOutput   `pulumi:"networkVolumeId"`
	ScalerType          pulumi.StringPtrOutput   `pulumi:"scalerType"`
	ScalerValue         pulumi.IntPtrOutput      `pulumi:"scalerValue"`
	TemplateId          pulumi.StringPtrOutput   `pulumi:"templateId"`
	Type                pulumi.StringPtrOutput   `pulumi:"type"`
	WorkersMax          pulumi.IntPtrOutput      `pulumi:"workersMax"`
	WorkersMin          pulumi.IntPtrOutput      `pulumi:"workersMin"`
}

// NewEndpoint registers a new resource with the given unique name, arguments, and options.
func NewEndpoint(ctx *pulumi.Context,
	name string, args *EndpointArgs, opts ...pulumi.ResourceOption) (*Endpoint, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Endpoint
	err := ctx.RegisterResource("runpod:index:Endpoint", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetEndpoint gets an existing Endpoint resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetEndpoint(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *EndpointState, opts ...pulumi.ResourceOption) (*Endpoint, error) {
	var resource Endpoint
	err := ctx.ReadResource("runpod:index:Endpoint", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Endpoint resources.
type endpointState struct {
}

type EndpointState struct {
}

func (EndpointState) ElementType() reflect.Type {
	return reflect.TypeOf((*endpointState)(nil)).Elem()
}

type endpointArgs struct {
	AllowedCudaVersions *string           `pulumi:"allowedCudaVersions"`
	BindEndpoint        *bool             `pulumi:"bindEndpoint"`
	Env                 map[string]string `pulumi:"env"`
	ExecutionTimeoutMs  *int              `pulumi:"executionTimeoutMs"`
	FlashBootType       *string           `pulumi:"flashBootType"`
	FlashEnvironmentId  *string           `pulumi:"flashEnvironmentId"`
	GpuCount            *int              `pulumi:"gpuCount"`
	GpuIds              *string           `pulumi:"gpuIds"`
	HubReleaseId        *string           `pulumi:"hubReleaseId"`
	IdleTimeout         *int              `pulumi:"idleTimeout"`
	InstanceIds         []string          `pulumi:"instanceIds"`
	Locations           *string           `pulumi:"locations"`
	MinCudaVersion      *string           `pulumi:"minCudaVersion"`
	ModelName           *string           `pulumi:"modelName"`
	ModelReferences     []string          `pulumi:"modelReferences"`
	Name                string            `pulumi:"name"`
	NetworkVolumeId     *string           `pulumi:"networkVolumeId"`
	ScalerType          *string           `pulumi:"scalerType"`
	ScalerValue         *int              `pulumi:"scalerValue"`
	TemplateId          *string           `pulumi:"templateId"`
	Type                *string           `pulumi:"type"`
	WorkersMax          *int              `pulumi:"workersMax"`
	WorkersMin          *int              `pulumi:"workersMin"`
}

// The set of arguments for constructing a Endpoint resource.
type EndpointArgs struct {
	AllowedCudaVersions pulumi.StringPtrInput
	BindEndpoint        pulumi.BoolPtrInput
	Env                 pulumi.StringMapInput
	ExecutionTimeoutMs  pulumi.IntPtrInput
	FlashBootType       pulumi.StringPtrInput
	FlashEnvironmentId  pulumi.StringPtrInput
	GpuCount            pulumi.IntPtrInput
	GpuIds              pulumi.StringPtrInput
	HubReleaseId        pulumi.StringPtrInput
	IdleTimeout         pulumi.IntPtrInput
	InstanceIds         pulumi.StringArrayInput
	Locations           pulumi.StringPtrInput
	MinCudaVersion      pulumi.StringPtrInput
	ModelName           pulumi.StringPtrInput
	ModelReferences     pulumi.StringArrayInput
	Name                pulumi.StringInput
	NetworkVolumeId     pulumi.StringPtrInput
	ScalerType          pulumi.StringPtrInput
	ScalerValue         pulumi.IntPtrInput
	TemplateId          pulumi.StringPtrInput
	Type                pulumi.StringPtrInput
	WorkersMax          pulumi.IntPtrInput
	WorkersMin          pulumi.IntPtrInput
}

func (EndpointArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*endpointArgs)(nil)).Elem()
}

type EndpointInput interface {
	pulumi.Input

	ToEndpointOutput() EndpointOutput
	ToEndpointOutputWithContext(ctx context.Context) EndpointOutput
}

func (*Endpoint) ElementType() reflect.Type {
	return reflect.TypeOf((**Endpoint)(nil)).Elem()
}

func (i *Endpoint) ToEndpointOutput() EndpointOutput {
	return i.ToEndpointOutputWithContext(context.Background())
}

func (i *Endpoint) ToEndpointOutputWithContext(ctx context.Context) EndpointOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EndpointOutput)
}

// EndpointArrayInput is an input type that accepts EndpointArray and EndpointArrayOutput values.
// You can construct a concrete instance of `EndpointArrayInput` via:
//
//	EndpointArray{ EndpointArgs{...} }
type EndpointArrayInput interface {
	pulumi.Input

	ToEndpointArrayOutput() EndpointArrayOutput
	ToEndpointArrayOutputWithContext(context.Context) EndpointArrayOutput
}

type EndpointArray []EndpointInput

func (EndpointArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Endpoint)(nil)).Elem()
}

func (i EndpointArray) ToEndpointArrayOutput() EndpointArrayOutput {
	return i.ToEndpointArrayOutputWithContext(context.Background())
}

func (i EndpointArray) ToEndpointArrayOutputWithContext(ctx context.Context) EndpointArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EndpointArrayOutput)
}

// EndpointMapInput is an input type that accepts EndpointMap and EndpointMapOutput values.
// You can construct a concrete instance of `EndpointMapInput` via:
//
//	EndpointMap{ "key": EndpointArgs{...} }
type EndpointMapInput interface {
	pulumi.Input

	ToEndpointMapOutput() EndpointMapOutput
	ToEndpointMapOutputWithContext(context.Context) EndpointMapOutput
}

type EndpointMap map[string]EndpointInput

func (EndpointMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Endpoint)(nil)).Elem()
}

func (i EndpointMap) ToEndpointMapOutput() EndpointMapOutput {
	return i.ToEndpointMapOutputWithContext(context.Background())
}

func (i EndpointMap) ToEndpointMapOutputWithContext(ctx context.Context) EndpointMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EndpointMapOutput)
}

type EndpointOutput struct{ *pulumi.OutputState }

func (EndpointOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Endpoint)(nil)).Elem()
}

func (o EndpointOutput) ToEndpointOutput() EndpointOutput {
	return o
}

func (o EndpointOutput) ToEndpointOutputWithContext(ctx context.Context) EndpointOutput {
	return o
}

func (o EndpointOutput) AllowedCudaVersions() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Endpoint) pulumi.StringPtrOutput { return v.AllowedCudaVersions }).(pulumi.StringPtrOutput)
}

func (o EndpointOutput) BindEndpoint() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Endpoint) pulumi.BoolPtrOutput { return v.BindEndpoint }).(pulumi.BoolPtrOutput)
}

func (o EndpointOutput) EndpointId() pulumi.StringOutput {
	return o.ApplyT(func(v *Endpoint) pulumi.StringOutput { return v.EndpointId }).(pulumi.StringOutput)
}

func (o EndpointOutput) Env() pulumi.StringMapOutput {
	return o.ApplyT(func(v *Endpoint) pulumi.StringMapOutput { return v.Env }).(pulumi.StringMapOutput)
}

func (o EndpointOutput) ExecutionTimeoutMs() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Endpoint) pulumi.IntPtrOutput { return v.ExecutionTimeoutMs }).(pulumi.IntPtrOutput)
}

func (o EndpointOutput) FlashBootType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Endpoint) pulumi.StringPtrOutput { return v.FlashBootType }).(pulumi.StringPtrOutput)
}

func (o EndpointOutput) FlashEnvironmentId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Endpoint) pulumi.StringPtrOutput { return v.FlashEnvironmentId }).(pulumi.StringPtrOutput)
}

func (o EndpointOutput) GpuCount() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Endpoint) pulumi.IntPtrOutput { return v.GpuCount }).(pulumi.IntPtrOutput)
}

func (o EndpointOutput) GpuIds() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Endpoint) pulumi.StringPtrOutput { return v.GpuIds }).(pulumi.StringPtrOutput)
}

func (o EndpointOutput) HubReleaseId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Endpoint) pulumi.StringPtrOutput { return v.HubReleaseId }).(pulumi.StringPtrOutput)
}

func (o EndpointOutput) IdleTimeout() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Endpoint) pulumi.IntPtrOutput { return v.IdleTimeout }).(pulumi.IntPtrOutput)
}

func (o EndpointOutput) InstanceIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Endpoint) pulumi.StringArrayOutput { return v.InstanceIds }).(pulumi.StringArrayOutput)
}

func (o EndpointOutput) Locations() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Endpoint) pulumi.StringPtrOutput { return v.Locations }).(pulumi.StringPtrOutput)
}

func (o EndpointOutput) MinCudaVersion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Endpoint) pulumi.StringPtrOutput { return v.MinCudaVersion }).(pulumi.StringPtrOutput)
}

func (o EndpointOutput) ModelName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Endpoint) pulumi.StringPtrOutput { return v.ModelName }).(pulumi.StringPtrOutput)
}

func (o EndpointOutput) ModelReferences() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Endpoint) pulumi.StringArrayOutput { return v.ModelReferences }).(pulumi.StringArrayOutput)
}

func (o EndpointOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Endpoint) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o EndpointOutput) NetworkVolumeId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Endpoint) pulumi.StringPtrOutput { return v.NetworkVolumeId }).(pulumi.StringPtrOutput)
}

func (o EndpointOutput) ScalerType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Endpoint) pulumi.StringPtrOutput { return v.ScalerType }).(pulumi.StringPtrOutput)
}

func (o EndpointOutput) ScalerValue() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Endpoint) pulumi.IntPtrOutput { return v.ScalerValue }).(pulumi.IntPtrOutput)
}

func (o EndpointOutput) TemplateId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Endpoint) pulumi.StringPtrOutput { return v.TemplateId }).(pulumi.StringPtrOutput)
}

func (o EndpointOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Endpoint) pulumi.StringPtrOutput { return v.Type }).(pulumi.StringPtrOutput)
}

func (o EndpointOutput) WorkersMax() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Endpoint) pulumi.IntPtrOutput { return v.WorkersMax }).(pulumi.IntPtrOutput)
}

func (o EndpointOutput) WorkersMin() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Endpoint) pulumi.IntPtrOutput { return v.WorkersMin }).(pulumi.IntPtrOutput)
}

type EndpointArrayOutput struct{ *pulumi.OutputState }

func (EndpointArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Endpoint)(nil)).Elem()
}

func (o EndpointArrayOutput) ToEndpointArrayOutput() EndpointArrayOutput {
	return o
}

func (o EndpointArrayOutput) ToEndpointArrayOutputWithContext(ctx context.Context) EndpointArrayOutput {
	return o
}

func (o EndpointArrayOutput) Index(i pulumi.IntInput) EndpointOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Endpoint {
		return vs[0].([]*Endpoint)[vs[1].(int)]
	}).(EndpointOutput)
}

type EndpointMapOutput struct{ *pulumi.OutputState }

func (EndpointMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Endpoint)(nil)).Elem()
}

func (o EndpointMapOutput) ToEndpointMapOutput() EndpointMapOutput {
	return o
}

func (o EndpointMapOutput) ToEndpointMapOutputWithContext(ctx context.Context) EndpointMapOutput {
	return o
}

func (o EndpointMapOutput) MapIndex(k pulumi.StringInput) EndpointOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Endpoint {
		return vs[0].(map[string]*Endpoint)[vs[1].(string)]
	}).(EndpointOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*EndpointInput)(nil)).Elem(), &Endpoint{})
	pulumi.RegisterInputType(reflect.TypeOf((*EndpointArrayInput)(nil)).Elem(), EndpointArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*EndpointMapInput)(nil)).Elem(), EndpointMap{})
	pulumi.RegisterOutputType(EndpointOutput{})
	pulumi.RegisterOutputType(EndpointArrayOutput{})
	pulumi.RegisterOutputType(EndpointMapOutput{})
}
