// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package runpod

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/runpod/pulumi-runpod/sdk/go/runpod/internal"
)

func GetGpuTypes(ctx *pulumi.Context, args *GetGpuTypesArgs, opts ...pulumi.InvokeOption) (*GetGpuTypesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetGpuTypesResult
	err := ctx.Invoke("runpod:index:getGpuTypes", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetGpuTypesArgs struct {
}

type GetGpuTypesResult struct {
	GpuTypes []GpuTypeOutput `pulumi:"gpuTypes"`
}

func GetGpuTypesOutput(ctx *pulumi.Context, args GetGpuTypesOutputArgs, opts ...pulumi.InvokeOption) GetGpuTypesResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetGpuTypesResultOutput, error) {
			args := v.(GetGpuTypesArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("runpod:index:getGpuTypes", args, GetGpuTypesResultOutput{}, options).(GetGpuTypesResultOutput), nil
		}).(GetGpuTypesResultOutput)
}

type GetGpuTypesOutputArgs struct {
}

func (GetGpuTypesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetGpuTypesArgs)(nil)).Elem()
}

type GetGpuTypesResultOutput struct{ *pulumi.OutputState }

func (GetGpuTypesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetGpuTypesResult)(nil)).Elem()
}

func (o GetGpuTypesResultOutput) ToGetGpuTypesResultOutput() GetGpuTypesResultOutput {
	return o
}

func (o GetGpuTypesResultOutput) ToGetGpuTypesResultOutputWithContext(ctx context.Context) GetGpuTypesResultOutput {
	return o
}

func (o GetGpuTypesResultOutput) GpuTypes() GpuTypeOutputArrayOutput {
	return o.ApplyT(func(v GetGpuTypesResult) []GpuTypeOutput { return v.GpuTypes }).(GpuTypeOutputArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetGpuTypesResultOutput{})
}
