// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package runpod

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/runpod/pulumi-runpod/sdk/go/runpod/internal"
)

var _ = internal.GetEnvOrDefault

type GpuTypeOutput struct {
	CommunityCloud bool    `pulumi:"communityCloud"`
	CommunityPrice float64 `pulumi:"communityPrice"`
	DisplayName    string  `pulumi:"displayName"`
	Id             string  `pulumi:"id"`
	MaxGpuCount    int     `pulumi:"maxGpuCount"`
	MemoryInGb     int     `pulumi:"memoryInGb"`
	SecureCloud    bool    `pulumi:"secureCloud"`
	SecurePrice    float64 `pulumi:"securePrice"`
}

type GpuTypeOutputOutput struct{ *pulumi.OutputState }

func (GpuTypeOutputOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GpuTypeOutput)(nil)).Elem()
}

func (o GpuTypeOutputOutput) ToGpuTypeOutputOutput() GpuTypeOutputOutput {
	return o
}

func (o GpuTypeOutputOutput) ToGpuTypeOutputOutputWithContext(ctx context.Context) GpuTypeOutputOutput {
	return o
}

func (o GpuTypeOutputOutput) CommunityCloud() pulumi.BoolOutput {
	return o.ApplyT(func(v GpuTypeOutput) bool { return v.CommunityCloud }).(pulumi.BoolOutput)
}

func (o GpuTypeOutputOutput) CommunityPrice() pulumi.Float64Output {
	return o.ApplyT(func(v GpuTypeOutput) float64 { return v.CommunityPrice }).(pulumi.Float64Output)
}

func (o GpuTypeOutputOutput) DisplayName() pulumi.StringOutput {
	return o.ApplyT(func(v GpuTypeOutput) string { return v.DisplayName }).(pulumi.StringOutput)
}

func (o GpuTypeOutputOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GpuTypeOutput) string { return v.Id }).(pulumi.StringOutput)
}

func (o GpuTypeOutputOutput) MaxGpuCount() pulumi.IntOutput {
	return o.ApplyT(func(v GpuTypeOutput) int { return v.MaxGpuCount }).(pulumi.IntOutput)
}

func (o GpuTypeOutputOutput) MemoryInGb() pulumi.IntOutput {
	return o.ApplyT(func(v GpuTypeOutput) int { return v.MemoryInGb }).(pulumi.IntOutput)
}

func (o GpuTypeOutputOutput) SecureCloud() pulumi.BoolOutput {
	return o.ApplyT(func(v GpuTypeOutput) bool { return v.SecureCloud }).(pulumi.BoolOutput)
}

func (o GpuTypeOutputOutput) SecurePrice() pulumi.Float64Output {
	return o.ApplyT(func(v GpuTypeOutput) float64 { return v.SecurePrice }).(pulumi.Float64Output)
}

type GpuTypeOutputArrayOutput struct{ *pulumi.OutputState }

func (GpuTypeOutputArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GpuTypeOutput)(nil)).Elem()
}

func (o GpuTypeOutputArrayOutput) ToGpuTypeOutputArrayOutput() GpuTypeOutputArrayOutput {
	return o
}

func (o GpuTypeOutputArrayOutput) ToGpuTypeOutputArrayOutputWithContext(ctx context.Context) GpuTypeOutputArrayOutput {
	return o
}

func (o GpuTypeOutputArrayOutput) Index(i pulumi.IntInput) GpuTypeOutputOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GpuTypeOutput {
		return vs[0].([]GpuTypeOutput)[vs[1].(int)]
	}).(GpuTypeOutputOutput)
}

func init() {
	pulumi.RegisterOutputType(GpuTypeOutputOutput{})
	pulumi.RegisterOutputType(GpuTypeOutputArrayOutput{})
}
