// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package runpod

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/runpod/pulumi-runpod/sdk/go/runpod/internal"
)

var _ = internal.GetEnvOrDefault

type GpuTypeOutput struct {
	// Whether the GPU is available in community cloud.
	CommunityCloud bool `pulumi:"communityCloud"`
	// The price per hour in community cloud (USD).
	CommunityPrice float64 `pulumi:"communityPrice"`
	// The display name of the GPU type.
	DisplayName string `pulumi:"displayName"`
	// The unique identifier of the GPU type.
	Id string `pulumi:"id"`
	// The maximum number of this GPU type that can be allocated.
	MaxGpuCount int `pulumi:"maxGpuCount"`
	// The amount of VRAM in GB.
	MemoryInGb int `pulumi:"memoryInGb"`
	// Whether the GPU is available in secure cloud.
	SecureCloud bool `pulumi:"secureCloud"`
	// The price per hour in secure cloud (USD).
	SecurePrice float64 `pulumi:"securePrice"`
}

type GpuTypeOutputOutput struct{ *pulumi.OutputState }

func (GpuTypeOutputOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GpuTypeOutput)(nil)).Elem()
}

func (o GpuTypeOutputOutput) ToGpuTypeOutputOutput() GpuTypeOutputOutput {
	return o
}

func (o GpuTypeOutputOutput) ToGpuTypeOutputOutputWithContext(ctx context.Context) GpuTypeOutputOutput {
	return o
}

// Whether the GPU is available in community cloud.
func (o GpuTypeOutputOutput) CommunityCloud() pulumi.BoolOutput {
	return o.ApplyT(func(v GpuTypeOutput) bool { return v.CommunityCloud }).(pulumi.BoolOutput)
}

// The price per hour in community cloud (USD).
func (o GpuTypeOutputOutput) CommunityPrice() pulumi.Float64Output {
	return o.ApplyT(func(v GpuTypeOutput) float64 { return v.CommunityPrice }).(pulumi.Float64Output)
}

// The display name of the GPU type.
func (o GpuTypeOutputOutput) DisplayName() pulumi.StringOutput {
	return o.ApplyT(func(v GpuTypeOutput) string { return v.DisplayName }).(pulumi.StringOutput)
}

// The unique identifier of the GPU type.
func (o GpuTypeOutputOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GpuTypeOutput) string { return v.Id }).(pulumi.StringOutput)
}

// The maximum number of this GPU type that can be allocated.
func (o GpuTypeOutputOutput) MaxGpuCount() pulumi.IntOutput {
	return o.ApplyT(func(v GpuTypeOutput) int { return v.MaxGpuCount }).(pulumi.IntOutput)
}

// The amount of VRAM in GB.
func (o GpuTypeOutputOutput) MemoryInGb() pulumi.IntOutput {
	return o.ApplyT(func(v GpuTypeOutput) int { return v.MemoryInGb }).(pulumi.IntOutput)
}

// Whether the GPU is available in secure cloud.
func (o GpuTypeOutputOutput) SecureCloud() pulumi.BoolOutput {
	return o.ApplyT(func(v GpuTypeOutput) bool { return v.SecureCloud }).(pulumi.BoolOutput)
}

// The price per hour in secure cloud (USD).
func (o GpuTypeOutputOutput) SecurePrice() pulumi.Float64Output {
	return o.ApplyT(func(v GpuTypeOutput) float64 { return v.SecurePrice }).(pulumi.Float64Output)
}

type GpuTypeOutputArrayOutput struct{ *pulumi.OutputState }

func (GpuTypeOutputArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GpuTypeOutput)(nil)).Elem()
}

func (o GpuTypeOutputArrayOutput) ToGpuTypeOutputArrayOutput() GpuTypeOutputArrayOutput {
	return o
}

func (o GpuTypeOutputArrayOutput) ToGpuTypeOutputArrayOutputWithContext(ctx context.Context) GpuTypeOutputArrayOutput {
	return o
}

func (o GpuTypeOutputArrayOutput) Index(i pulumi.IntInput) GpuTypeOutputOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GpuTypeOutput {
		return vs[0].([]GpuTypeOutput)[vs[1].(int)]
	}).(GpuTypeOutputOutput)
}

type SavingsPlan struct {
	// The length of the savings plan.
	PlanLength *string `pulumi:"planLength"`
	// The upfront cost for the savings plan.
	UpfrontCost *float64 `pulumi:"upfrontCost"`
}

// SavingsPlanInput is an input type that accepts SavingsPlanArgs and SavingsPlanOutput values.
// You can construct a concrete instance of `SavingsPlanInput` via:
//
//	SavingsPlanArgs{...}
type SavingsPlanInput interface {
	pulumi.Input

	ToSavingsPlanOutput() SavingsPlanOutput
	ToSavingsPlanOutputWithContext(context.Context) SavingsPlanOutput
}

type SavingsPlanArgs struct {
	// The length of the savings plan.
	PlanLength pulumi.StringPtrInput `pulumi:"planLength"`
	// The upfront cost for the savings plan.
	UpfrontCost pulumi.Float64PtrInput `pulumi:"upfrontCost"`
}

func (SavingsPlanArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*SavingsPlan)(nil)).Elem()
}

func (i SavingsPlanArgs) ToSavingsPlanOutput() SavingsPlanOutput {
	return i.ToSavingsPlanOutputWithContext(context.Background())
}

func (i SavingsPlanArgs) ToSavingsPlanOutputWithContext(ctx context.Context) SavingsPlanOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SavingsPlanOutput)
}

func (i SavingsPlanArgs) ToSavingsPlanPtrOutput() SavingsPlanPtrOutput {
	return i.ToSavingsPlanPtrOutputWithContext(context.Background())
}

func (i SavingsPlanArgs) ToSavingsPlanPtrOutputWithContext(ctx context.Context) SavingsPlanPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SavingsPlanOutput).ToSavingsPlanPtrOutputWithContext(ctx)
}

// SavingsPlanPtrInput is an input type that accepts SavingsPlanArgs, SavingsPlanPtr and SavingsPlanPtrOutput values.
// You can construct a concrete instance of `SavingsPlanPtrInput` via:
//
//	        SavingsPlanArgs{...}
//
//	or:
//
//	        nil
type SavingsPlanPtrInput interface {
	pulumi.Input

	ToSavingsPlanPtrOutput() SavingsPlanPtrOutput
	ToSavingsPlanPtrOutputWithContext(context.Context) SavingsPlanPtrOutput
}

type savingsPlanPtrType SavingsPlanArgs

func SavingsPlanPtr(v *SavingsPlanArgs) SavingsPlanPtrInput {
	return (*savingsPlanPtrType)(v)
}

func (*savingsPlanPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**SavingsPlan)(nil)).Elem()
}

func (i *savingsPlanPtrType) ToSavingsPlanPtrOutput() SavingsPlanPtrOutput {
	return i.ToSavingsPlanPtrOutputWithContext(context.Background())
}

func (i *savingsPlanPtrType) ToSavingsPlanPtrOutputWithContext(ctx context.Context) SavingsPlanPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SavingsPlanPtrOutput)
}

type SavingsPlanOutput struct{ *pulumi.OutputState }

func (SavingsPlanOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*SavingsPlan)(nil)).Elem()
}

func (o SavingsPlanOutput) ToSavingsPlanOutput() SavingsPlanOutput {
	return o
}

func (o SavingsPlanOutput) ToSavingsPlanOutputWithContext(ctx context.Context) SavingsPlanOutput {
	return o
}

func (o SavingsPlanOutput) ToSavingsPlanPtrOutput() SavingsPlanPtrOutput {
	return o.ToSavingsPlanPtrOutputWithContext(context.Background())
}

func (o SavingsPlanOutput) ToSavingsPlanPtrOutputWithContext(ctx context.Context) SavingsPlanPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v SavingsPlan) *SavingsPlan {
		return &v
	}).(SavingsPlanPtrOutput)
}

// The length of the savings plan.
func (o SavingsPlanOutput) PlanLength() pulumi.StringPtrOutput {
	return o.ApplyT(func(v SavingsPlan) *string { return v.PlanLength }).(pulumi.StringPtrOutput)
}

// The upfront cost for the savings plan.
func (o SavingsPlanOutput) UpfrontCost() pulumi.Float64PtrOutput {
	return o.ApplyT(func(v SavingsPlan) *float64 { return v.UpfrontCost }).(pulumi.Float64PtrOutput)
}

type SavingsPlanPtrOutput struct{ *pulumi.OutputState }

func (SavingsPlanPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SavingsPlan)(nil)).Elem()
}

func (o SavingsPlanPtrOutput) ToSavingsPlanPtrOutput() SavingsPlanPtrOutput {
	return o
}

func (o SavingsPlanPtrOutput) ToSavingsPlanPtrOutputWithContext(ctx context.Context) SavingsPlanPtrOutput {
	return o
}

func (o SavingsPlanPtrOutput) Elem() SavingsPlanOutput {
	return o.ApplyT(func(v *SavingsPlan) SavingsPlan {
		if v != nil {
			return *v
		}
		var ret SavingsPlan
		return ret
	}).(SavingsPlanOutput)
}

// The length of the savings plan.
func (o SavingsPlanPtrOutput) PlanLength() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SavingsPlan) *string {
		if v == nil {
			return nil
		}
		return v.PlanLength
	}).(pulumi.StringPtrOutput)
}

// The upfront cost for the savings plan.
func (o SavingsPlanPtrOutput) UpfrontCost() pulumi.Float64PtrOutput {
	return o.ApplyT(func(v *SavingsPlan) *float64 {
		if v == nil {
			return nil
		}
		return v.UpfrontCost
	}).(pulumi.Float64PtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SavingsPlanInput)(nil)).Elem(), SavingsPlanArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*SavingsPlanPtrInput)(nil)).Elem(), SavingsPlanArgs{})
	pulumi.RegisterOutputType(GpuTypeOutputOutput{})
	pulumi.RegisterOutputType(GpuTypeOutputArrayOutput{})
	pulumi.RegisterOutputType(SavingsPlanOutput{})
	pulumi.RegisterOutputType(SavingsPlanPtrOutput{})
}
