// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package runpod

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/runpod/pulumi-runpod/sdk/go/runpod/internal"
)

var _ = internal.GetEnvOrDefault

type CPUFlavorOutput struct {
	// Disk limit per vCPU (in GB).
	DiskLimitPerVcpu int `pulumi:"diskLimitPerVcpu"`
	// The human-readable name of the CPU flavor.
	DisplayName string `pulumi:"displayName"`
	// The group this flavor belongs to.
	GroupId string `pulumi:"groupId"`
	// The display name of the flavor group.
	GroupName string `pulumi:"groupName"`
	// The unique identifier of the CPU flavor (used as flavorId in instanceId).
	Id string `pulumi:"id"`
	// The maximum number of vCPUs for this flavor.
	MaxVcpu int `pulumi:"maxVcpu"`
	// The minimum number of vCPUs for this flavor.
	MinVcpu float64 `pulumi:"minVcpu"`
	// RAM allocated per vCPU (in GB).
	RamMultiplier float64 `pulumi:"ramMultiplier"`
	// Whether vCPUs are burstable.
	VcpuBurstable bool `pulumi:"vcpuBurstable"`
}

type CPUFlavorOutputOutput struct{ *pulumi.OutputState }

func (CPUFlavorOutputOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*CPUFlavorOutput)(nil)).Elem()
}

func (o CPUFlavorOutputOutput) ToCPUFlavorOutputOutput() CPUFlavorOutputOutput {
	return o
}

func (o CPUFlavorOutputOutput) ToCPUFlavorOutputOutputWithContext(ctx context.Context) CPUFlavorOutputOutput {
	return o
}

// Disk limit per vCPU (in GB).
func (o CPUFlavorOutputOutput) DiskLimitPerVcpu() pulumi.IntOutput {
	return o.ApplyT(func(v CPUFlavorOutput) int { return v.DiskLimitPerVcpu }).(pulumi.IntOutput)
}

// The human-readable name of the CPU flavor.
func (o CPUFlavorOutputOutput) DisplayName() pulumi.StringOutput {
	return o.ApplyT(func(v CPUFlavorOutput) string { return v.DisplayName }).(pulumi.StringOutput)
}

// The group this flavor belongs to.
func (o CPUFlavorOutputOutput) GroupId() pulumi.StringOutput {
	return o.ApplyT(func(v CPUFlavorOutput) string { return v.GroupId }).(pulumi.StringOutput)
}

// The display name of the flavor group.
func (o CPUFlavorOutputOutput) GroupName() pulumi.StringOutput {
	return o.ApplyT(func(v CPUFlavorOutput) string { return v.GroupName }).(pulumi.StringOutput)
}

// The unique identifier of the CPU flavor (used as flavorId in instanceId).
func (o CPUFlavorOutputOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v CPUFlavorOutput) string { return v.Id }).(pulumi.StringOutput)
}

// The maximum number of vCPUs for this flavor.
func (o CPUFlavorOutputOutput) MaxVcpu() pulumi.IntOutput {
	return o.ApplyT(func(v CPUFlavorOutput) int { return v.MaxVcpu }).(pulumi.IntOutput)
}

// The minimum number of vCPUs for this flavor.
func (o CPUFlavorOutputOutput) MinVcpu() pulumi.Float64Output {
	return o.ApplyT(func(v CPUFlavorOutput) float64 { return v.MinVcpu }).(pulumi.Float64Output)
}

// RAM allocated per vCPU (in GB).
func (o CPUFlavorOutputOutput) RamMultiplier() pulumi.Float64Output {
	return o.ApplyT(func(v CPUFlavorOutput) float64 { return v.RamMultiplier }).(pulumi.Float64Output)
}

// Whether vCPUs are burstable.
func (o CPUFlavorOutputOutput) VcpuBurstable() pulumi.BoolOutput {
	return o.ApplyT(func(v CPUFlavorOutput) bool { return v.VcpuBurstable }).(pulumi.BoolOutput)
}

type CPUFlavorOutputArrayOutput struct{ *pulumi.OutputState }

func (CPUFlavorOutputArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]CPUFlavorOutput)(nil)).Elem()
}

func (o CPUFlavorOutputArrayOutput) ToCPUFlavorOutputArrayOutput() CPUFlavorOutputArrayOutput {
	return o
}

func (o CPUFlavorOutputArrayOutput) ToCPUFlavorOutputArrayOutputWithContext(ctx context.Context) CPUFlavorOutputArrayOutput {
	return o
}

func (o CPUFlavorOutputArrayOutput) Index(i pulumi.IntInput) CPUFlavorOutputOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) CPUFlavorOutput {
		return vs[0].([]CPUFlavorOutput)[vs[1].(int)]
	}).(CPUFlavorOutputOutput)
}

type DataCenterOutput struct {
	// Compliance certifications held by this data center.
	Compliance []string `pulumi:"compliance"`
	// Whether this data center is part of the global network.
	GlobalNetwork bool `pulumi:"globalNetwork"`
	// GPU availability within this data center.
	GpuAvailability []GpuAvailabilityItem `pulumi:"gpuAvailability"`
	// The unique identifier of the data center (used as dataCenterId).
	Id string `pulumi:"id"`
	// Whether this data center is publicly listed.
	Listed bool `pulumi:"listed"`
	// The geographic location of the data center.
	Location string `pulumi:"location"`
	// The display name of the data center.
	Name string `pulumi:"name"`
	// The broad region (e.g. NORTH_AMERICA, EUROPE).
	Region string `pulumi:"region"`
	// Whether this data center supports network volumes.
	StorageSupport bool `pulumi:"storageSupport"`
}

type DataCenterOutputOutput struct{ *pulumi.OutputState }

func (DataCenterOutputOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DataCenterOutput)(nil)).Elem()
}

func (o DataCenterOutputOutput) ToDataCenterOutputOutput() DataCenterOutputOutput {
	return o
}

func (o DataCenterOutputOutput) ToDataCenterOutputOutputWithContext(ctx context.Context) DataCenterOutputOutput {
	return o
}

// Compliance certifications held by this data center.
func (o DataCenterOutputOutput) Compliance() pulumi.StringArrayOutput {
	return o.ApplyT(func(v DataCenterOutput) []string { return v.Compliance }).(pulumi.StringArrayOutput)
}

// Whether this data center is part of the global network.
func (o DataCenterOutputOutput) GlobalNetwork() pulumi.BoolOutput {
	return o.ApplyT(func(v DataCenterOutput) bool { return v.GlobalNetwork }).(pulumi.BoolOutput)
}

// GPU availability within this data center.
func (o DataCenterOutputOutput) GpuAvailability() GpuAvailabilityItemArrayOutput {
	return o.ApplyT(func(v DataCenterOutput) []GpuAvailabilityItem { return v.GpuAvailability }).(GpuAvailabilityItemArrayOutput)
}

// The unique identifier of the data center (used as dataCenterId).
func (o DataCenterOutputOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v DataCenterOutput) string { return v.Id }).(pulumi.StringOutput)
}

// Whether this data center is publicly listed.
func (o DataCenterOutputOutput) Listed() pulumi.BoolOutput {
	return o.ApplyT(func(v DataCenterOutput) bool { return v.Listed }).(pulumi.BoolOutput)
}

// The geographic location of the data center.
func (o DataCenterOutputOutput) Location() pulumi.StringOutput {
	return o.ApplyT(func(v DataCenterOutput) string { return v.Location }).(pulumi.StringOutput)
}

// The display name of the data center.
func (o DataCenterOutputOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v DataCenterOutput) string { return v.Name }).(pulumi.StringOutput)
}

// The broad region (e.g. NORTH_AMERICA, EUROPE).
func (o DataCenterOutputOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v DataCenterOutput) string { return v.Region }).(pulumi.StringOutput)
}

// Whether this data center supports network volumes.
func (o DataCenterOutputOutput) StorageSupport() pulumi.BoolOutput {
	return o.ApplyT(func(v DataCenterOutput) bool { return v.StorageSupport }).(pulumi.BoolOutput)
}

type DataCenterOutputArrayOutput struct{ *pulumi.OutputState }

func (DataCenterOutputArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]DataCenterOutput)(nil)).Elem()
}

func (o DataCenterOutputArrayOutput) ToDataCenterOutputArrayOutput() DataCenterOutputArrayOutput {
	return o
}

func (o DataCenterOutputArrayOutput) ToDataCenterOutputArrayOutputWithContext(ctx context.Context) DataCenterOutputArrayOutput {
	return o
}

func (o DataCenterOutputArrayOutput) Index(i pulumi.IntInput) DataCenterOutputOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) DataCenterOutput {
		return vs[0].([]DataCenterOutput)[vs[1].(int)]
	}).(DataCenterOutputOutput)
}

type EndpointNetworkVolumeBinding struct {
	DataCenterId    string `pulumi:"dataCenterId"`
	NetworkVolumeId string `pulumi:"networkVolumeId"`
}

type EndpointNetworkVolumeBindingOutput struct{ *pulumi.OutputState }

func (EndpointNetworkVolumeBindingOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*EndpointNetworkVolumeBinding)(nil)).Elem()
}

func (o EndpointNetworkVolumeBindingOutput) ToEndpointNetworkVolumeBindingOutput() EndpointNetworkVolumeBindingOutput {
	return o
}

func (o EndpointNetworkVolumeBindingOutput) ToEndpointNetworkVolumeBindingOutputWithContext(ctx context.Context) EndpointNetworkVolumeBindingOutput {
	return o
}

func (o EndpointNetworkVolumeBindingOutput) DataCenterId() pulumi.StringOutput {
	return o.ApplyT(func(v EndpointNetworkVolumeBinding) string { return v.DataCenterId }).(pulumi.StringOutput)
}

func (o EndpointNetworkVolumeBindingOutput) NetworkVolumeId() pulumi.StringOutput {
	return o.ApplyT(func(v EndpointNetworkVolumeBinding) string { return v.NetworkVolumeId }).(pulumi.StringOutput)
}

type EndpointNetworkVolumeBindingArrayOutput struct{ *pulumi.OutputState }

func (EndpointNetworkVolumeBindingArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]EndpointNetworkVolumeBinding)(nil)).Elem()
}

func (o EndpointNetworkVolumeBindingArrayOutput) ToEndpointNetworkVolumeBindingArrayOutput() EndpointNetworkVolumeBindingArrayOutput {
	return o
}

func (o EndpointNetworkVolumeBindingArrayOutput) ToEndpointNetworkVolumeBindingArrayOutputWithContext(ctx context.Context) EndpointNetworkVolumeBindingArrayOutput {
	return o
}

func (o EndpointNetworkVolumeBindingArrayOutput) Index(i pulumi.IntInput) EndpointNetworkVolumeBindingOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) EndpointNetworkVolumeBinding {
		return vs[0].([]EndpointNetworkVolumeBinding)[vs[1].(int)]
	}).(EndpointNetworkVolumeBindingOutput)
}

type GpuAvailabilityItem struct {
	// Whether this GPU type is currently available at this data center.
	Available bool `pulumi:"available"`
	// The human-readable GPU type name.
	GpuTypeDisplayName string `pulumi:"gpuTypeDisplayName"`
	// The GPU type identifier.
	GpuTypeId string `pulumi:"gpuTypeId"`
	// Current stock status (e.g. High, Medium, Low).
	StockStatus string `pulumi:"stockStatus"`
}

type GpuAvailabilityItemOutput struct{ *pulumi.OutputState }

func (GpuAvailabilityItemOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GpuAvailabilityItem)(nil)).Elem()
}

func (o GpuAvailabilityItemOutput) ToGpuAvailabilityItemOutput() GpuAvailabilityItemOutput {
	return o
}

func (o GpuAvailabilityItemOutput) ToGpuAvailabilityItemOutputWithContext(ctx context.Context) GpuAvailabilityItemOutput {
	return o
}

// Whether this GPU type is currently available at this data center.
func (o GpuAvailabilityItemOutput) Available() pulumi.BoolOutput {
	return o.ApplyT(func(v GpuAvailabilityItem) bool { return v.Available }).(pulumi.BoolOutput)
}

// The human-readable GPU type name.
func (o GpuAvailabilityItemOutput) GpuTypeDisplayName() pulumi.StringOutput {
	return o.ApplyT(func(v GpuAvailabilityItem) string { return v.GpuTypeDisplayName }).(pulumi.StringOutput)
}

// The GPU type identifier.
func (o GpuAvailabilityItemOutput) GpuTypeId() pulumi.StringOutput {
	return o.ApplyT(func(v GpuAvailabilityItem) string { return v.GpuTypeId }).(pulumi.StringOutput)
}

// Current stock status (e.g. High, Medium, Low).
func (o GpuAvailabilityItemOutput) StockStatus() pulumi.StringOutput {
	return o.ApplyT(func(v GpuAvailabilityItem) string { return v.StockStatus }).(pulumi.StringOutput)
}

type GpuAvailabilityItemArrayOutput struct{ *pulumi.OutputState }

func (GpuAvailabilityItemArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GpuAvailabilityItem)(nil)).Elem()
}

func (o GpuAvailabilityItemArrayOutput) ToGpuAvailabilityItemArrayOutput() GpuAvailabilityItemArrayOutput {
	return o
}

func (o GpuAvailabilityItemArrayOutput) ToGpuAvailabilityItemArrayOutputWithContext(ctx context.Context) GpuAvailabilityItemArrayOutput {
	return o
}

func (o GpuAvailabilityItemArrayOutput) Index(i pulumi.IntInput) GpuAvailabilityItemOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GpuAvailabilityItem {
		return vs[0].([]GpuAvailabilityItem)[vs[1].(int)]
	}).(GpuAvailabilityItemOutput)
}

type GpuTypeOutput struct {
	// Whether the GPU is available in community cloud.
	CommunityCloud bool `pulumi:"communityCloud"`
	// The price per hour in community cloud (USD).
	CommunityPrice float64 `pulumi:"communityPrice"`
	// The display name of the GPU type.
	DisplayName string `pulumi:"displayName"`
	// The unique identifier of the GPU type.
	Id          string             `pulumi:"id"`
	LowestPrice *LowestPriceOutput `pulumi:"lowestPrice"`
	// The maximum number of this GPU type that can be allocated.
	MaxGpuCount int `pulumi:"maxGpuCount"`
	// The amount of VRAM in GB.
	MemoryInGb int `pulumi:"memoryInGb"`
	// Whether the GPU is available in secure cloud.
	SecureCloud bool `pulumi:"secureCloud"`
	// The price per hour in secure cloud (USD).
	SecurePrice float64 `pulumi:"securePrice"`
}

type GpuTypeOutputOutput struct{ *pulumi.OutputState }

func (GpuTypeOutputOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GpuTypeOutput)(nil)).Elem()
}

func (o GpuTypeOutputOutput) ToGpuTypeOutputOutput() GpuTypeOutputOutput {
	return o
}

func (o GpuTypeOutputOutput) ToGpuTypeOutputOutputWithContext(ctx context.Context) GpuTypeOutputOutput {
	return o
}

// Whether the GPU is available in community cloud.
func (o GpuTypeOutputOutput) CommunityCloud() pulumi.BoolOutput {
	return o.ApplyT(func(v GpuTypeOutput) bool { return v.CommunityCloud }).(pulumi.BoolOutput)
}

// The price per hour in community cloud (USD).
func (o GpuTypeOutputOutput) CommunityPrice() pulumi.Float64Output {
	return o.ApplyT(func(v GpuTypeOutput) float64 { return v.CommunityPrice }).(pulumi.Float64Output)
}

// The display name of the GPU type.
func (o GpuTypeOutputOutput) DisplayName() pulumi.StringOutput {
	return o.ApplyT(func(v GpuTypeOutput) string { return v.DisplayName }).(pulumi.StringOutput)
}

// The unique identifier of the GPU type.
func (o GpuTypeOutputOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GpuTypeOutput) string { return v.Id }).(pulumi.StringOutput)
}

func (o GpuTypeOutputOutput) LowestPrice() LowestPriceOutputPtrOutput {
	return o.ApplyT(func(v GpuTypeOutput) *LowestPriceOutput { return v.LowestPrice }).(LowestPriceOutputPtrOutput)
}

// The maximum number of this GPU type that can be allocated.
func (o GpuTypeOutputOutput) MaxGpuCount() pulumi.IntOutput {
	return o.ApplyT(func(v GpuTypeOutput) int { return v.MaxGpuCount }).(pulumi.IntOutput)
}

// The amount of VRAM in GB.
func (o GpuTypeOutputOutput) MemoryInGb() pulumi.IntOutput {
	return o.ApplyT(func(v GpuTypeOutput) int { return v.MemoryInGb }).(pulumi.IntOutput)
}

// Whether the GPU is available in secure cloud.
func (o GpuTypeOutputOutput) SecureCloud() pulumi.BoolOutput {
	return o.ApplyT(func(v GpuTypeOutput) bool { return v.SecureCloud }).(pulumi.BoolOutput)
}

// The price per hour in secure cloud (USD).
func (o GpuTypeOutputOutput) SecurePrice() pulumi.Float64Output {
	return o.ApplyT(func(v GpuTypeOutput) float64 { return v.SecurePrice }).(pulumi.Float64Output)
}

type GpuTypeOutputArrayOutput struct{ *pulumi.OutputState }

func (GpuTypeOutputArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GpuTypeOutput)(nil)).Elem()
}

func (o GpuTypeOutputArrayOutput) ToGpuTypeOutputArrayOutput() GpuTypeOutputArrayOutput {
	return o
}

func (o GpuTypeOutputArrayOutput) ToGpuTypeOutputArrayOutputWithContext(ctx context.Context) GpuTypeOutputArrayOutput {
	return o
}

func (o GpuTypeOutputArrayOutput) Index(i pulumi.IntInput) GpuTypeOutputOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GpuTypeOutput {
		return vs[0].([]GpuTypeOutput)[vs[1].(int)]
	}).(GpuTypeOutputOutput)
}

type LowestPriceOutput struct {
	MinimumBidPrice      float64 `pulumi:"minimumBidPrice"`
	RentedCount          int     `pulumi:"rentedCount"`
	StockStatus          string  `pulumi:"stockStatus"`
	TotalCount           int     `pulumi:"totalCount"`
	UninterruptablePrice float64 `pulumi:"uninterruptablePrice"`
}

type LowestPriceOutputOutput struct{ *pulumi.OutputState }

func (LowestPriceOutputOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LowestPriceOutput)(nil)).Elem()
}

func (o LowestPriceOutputOutput) ToLowestPriceOutputOutput() LowestPriceOutputOutput {
	return o
}

func (o LowestPriceOutputOutput) ToLowestPriceOutputOutputWithContext(ctx context.Context) LowestPriceOutputOutput {
	return o
}

func (o LowestPriceOutputOutput) MinimumBidPrice() pulumi.Float64Output {
	return o.ApplyT(func(v LowestPriceOutput) float64 { return v.MinimumBidPrice }).(pulumi.Float64Output)
}

func (o LowestPriceOutputOutput) RentedCount() pulumi.IntOutput {
	return o.ApplyT(func(v LowestPriceOutput) int { return v.RentedCount }).(pulumi.IntOutput)
}

func (o LowestPriceOutputOutput) StockStatus() pulumi.StringOutput {
	return o.ApplyT(func(v LowestPriceOutput) string { return v.StockStatus }).(pulumi.StringOutput)
}

func (o LowestPriceOutputOutput) TotalCount() pulumi.IntOutput {
	return o.ApplyT(func(v LowestPriceOutput) int { return v.TotalCount }).(pulumi.IntOutput)
}

func (o LowestPriceOutputOutput) UninterruptablePrice() pulumi.Float64Output {
	return o.ApplyT(func(v LowestPriceOutput) float64 { return v.UninterruptablePrice }).(pulumi.Float64Output)
}

type LowestPriceOutputPtrOutput struct{ *pulumi.OutputState }

func (LowestPriceOutputPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**LowestPriceOutput)(nil)).Elem()
}

func (o LowestPriceOutputPtrOutput) ToLowestPriceOutputPtrOutput() LowestPriceOutputPtrOutput {
	return o
}

func (o LowestPriceOutputPtrOutput) ToLowestPriceOutputPtrOutputWithContext(ctx context.Context) LowestPriceOutputPtrOutput {
	return o
}

func (o LowestPriceOutputPtrOutput) Elem() LowestPriceOutputOutput {
	return o.ApplyT(func(v *LowestPriceOutput) LowestPriceOutput {
		if v != nil {
			return *v
		}
		var ret LowestPriceOutput
		return ret
	}).(LowestPriceOutputOutput)
}

func (o LowestPriceOutputPtrOutput) MinimumBidPrice() pulumi.Float64PtrOutput {
	return o.ApplyT(func(v *LowestPriceOutput) *float64 {
		if v == nil {
			return nil
		}
		return &v.MinimumBidPrice
	}).(pulumi.Float64PtrOutput)
}

func (o LowestPriceOutputPtrOutput) RentedCount() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *LowestPriceOutput) *int {
		if v == nil {
			return nil
		}
		return &v.RentedCount
	}).(pulumi.IntPtrOutput)
}

func (o LowestPriceOutputPtrOutput) StockStatus() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *LowestPriceOutput) *string {
		if v == nil {
			return nil
		}
		return &v.StockStatus
	}).(pulumi.StringPtrOutput)
}

func (o LowestPriceOutputPtrOutput) TotalCount() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *LowestPriceOutput) *int {
		if v == nil {
			return nil
		}
		return &v.TotalCount
	}).(pulumi.IntPtrOutput)
}

func (o LowestPriceOutputPtrOutput) UninterruptablePrice() pulumi.Float64PtrOutput {
	return o.ApplyT(func(v *LowestPriceOutput) *float64 {
		if v == nil {
			return nil
		}
		return &v.UninterruptablePrice
	}).(pulumi.Float64PtrOutput)
}

type SavingsPlan struct {
	// The length of the savings plan.
	PlanLength *string `pulumi:"planLength"`
	// The upfront cost for the savings plan.
	UpfrontCost *float64 `pulumi:"upfrontCost"`
}

// SavingsPlanInput is an input type that accepts SavingsPlanArgs and SavingsPlanOutput values.
// You can construct a concrete instance of `SavingsPlanInput` via:
//
//	SavingsPlanArgs{...}
type SavingsPlanInput interface {
	pulumi.Input

	ToSavingsPlanOutput() SavingsPlanOutput
	ToSavingsPlanOutputWithContext(context.Context) SavingsPlanOutput
}

type SavingsPlanArgs struct {
	// The length of the savings plan.
	PlanLength pulumi.StringPtrInput `pulumi:"planLength"`
	// The upfront cost for the savings plan.
	UpfrontCost pulumi.Float64PtrInput `pulumi:"upfrontCost"`
}

func (SavingsPlanArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*SavingsPlan)(nil)).Elem()
}

func (i SavingsPlanArgs) ToSavingsPlanOutput() SavingsPlanOutput {
	return i.ToSavingsPlanOutputWithContext(context.Background())
}

func (i SavingsPlanArgs) ToSavingsPlanOutputWithContext(ctx context.Context) SavingsPlanOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SavingsPlanOutput)
}

func (i SavingsPlanArgs) ToSavingsPlanPtrOutput() SavingsPlanPtrOutput {
	return i.ToSavingsPlanPtrOutputWithContext(context.Background())
}

func (i SavingsPlanArgs) ToSavingsPlanPtrOutputWithContext(ctx context.Context) SavingsPlanPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SavingsPlanOutput).ToSavingsPlanPtrOutputWithContext(ctx)
}

// SavingsPlanPtrInput is an input type that accepts SavingsPlanArgs, SavingsPlanPtr and SavingsPlanPtrOutput values.
// You can construct a concrete instance of `SavingsPlanPtrInput` via:
//
//	        SavingsPlanArgs{...}
//
//	or:
//
//	        nil
type SavingsPlanPtrInput interface {
	pulumi.Input

	ToSavingsPlanPtrOutput() SavingsPlanPtrOutput
	ToSavingsPlanPtrOutputWithContext(context.Context) SavingsPlanPtrOutput
}

type savingsPlanPtrType SavingsPlanArgs

func SavingsPlanPtr(v *SavingsPlanArgs) SavingsPlanPtrInput {
	return (*savingsPlanPtrType)(v)
}

func (*savingsPlanPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**SavingsPlan)(nil)).Elem()
}

func (i *savingsPlanPtrType) ToSavingsPlanPtrOutput() SavingsPlanPtrOutput {
	return i.ToSavingsPlanPtrOutputWithContext(context.Background())
}

func (i *savingsPlanPtrType) ToSavingsPlanPtrOutputWithContext(ctx context.Context) SavingsPlanPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SavingsPlanPtrOutput)
}

type SavingsPlanOutput struct{ *pulumi.OutputState }

func (SavingsPlanOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*SavingsPlan)(nil)).Elem()
}

func (o SavingsPlanOutput) ToSavingsPlanOutput() SavingsPlanOutput {
	return o
}

func (o SavingsPlanOutput) ToSavingsPlanOutputWithContext(ctx context.Context) SavingsPlanOutput {
	return o
}

func (o SavingsPlanOutput) ToSavingsPlanPtrOutput() SavingsPlanPtrOutput {
	return o.ToSavingsPlanPtrOutputWithContext(context.Background())
}

func (o SavingsPlanOutput) ToSavingsPlanPtrOutputWithContext(ctx context.Context) SavingsPlanPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v SavingsPlan) *SavingsPlan {
		return &v
	}).(SavingsPlanPtrOutput)
}

// The length of the savings plan.
func (o SavingsPlanOutput) PlanLength() pulumi.StringPtrOutput {
	return o.ApplyT(func(v SavingsPlan) *string { return v.PlanLength }).(pulumi.StringPtrOutput)
}

// The upfront cost for the savings plan.
func (o SavingsPlanOutput) UpfrontCost() pulumi.Float64PtrOutput {
	return o.ApplyT(func(v SavingsPlan) *float64 { return v.UpfrontCost }).(pulumi.Float64PtrOutput)
}

type SavingsPlanPtrOutput struct{ *pulumi.OutputState }

func (SavingsPlanPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SavingsPlan)(nil)).Elem()
}

func (o SavingsPlanPtrOutput) ToSavingsPlanPtrOutput() SavingsPlanPtrOutput {
	return o
}

func (o SavingsPlanPtrOutput) ToSavingsPlanPtrOutputWithContext(ctx context.Context) SavingsPlanPtrOutput {
	return o
}

func (o SavingsPlanPtrOutput) Elem() SavingsPlanOutput {
	return o.ApplyT(func(v *SavingsPlan) SavingsPlan {
		if v != nil {
			return *v
		}
		var ret SavingsPlan
		return ret
	}).(SavingsPlanOutput)
}

// The length of the savings plan.
func (o SavingsPlanPtrOutput) PlanLength() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SavingsPlan) *string {
		if v == nil {
			return nil
		}
		return v.PlanLength
	}).(pulumi.StringPtrOutput)
}

// The upfront cost for the savings plan.
func (o SavingsPlanPtrOutput) UpfrontCost() pulumi.Float64PtrOutput {
	return o.ApplyT(func(v *SavingsPlan) *float64 {
		if v == nil {
			return nil
		}
		return v.UpfrontCost
	}).(pulumi.Float64PtrOutput)
}

type TemplatePortConfig struct {
	Name *string `pulumi:"name"`
	Port string  `pulumi:"port"`
}

// TemplatePortConfigInput is an input type that accepts TemplatePortConfigArgs and TemplatePortConfigOutput values.
// You can construct a concrete instance of `TemplatePortConfigInput` via:
//
//	TemplatePortConfigArgs{...}
type TemplatePortConfigInput interface {
	pulumi.Input

	ToTemplatePortConfigOutput() TemplatePortConfigOutput
	ToTemplatePortConfigOutputWithContext(context.Context) TemplatePortConfigOutput
}

type TemplatePortConfigArgs struct {
	Name pulumi.StringPtrInput `pulumi:"name"`
	Port pulumi.StringInput    `pulumi:"port"`
}

func (TemplatePortConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*TemplatePortConfig)(nil)).Elem()
}

func (i TemplatePortConfigArgs) ToTemplatePortConfigOutput() TemplatePortConfigOutput {
	return i.ToTemplatePortConfigOutputWithContext(context.Background())
}

func (i TemplatePortConfigArgs) ToTemplatePortConfigOutputWithContext(ctx context.Context) TemplatePortConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TemplatePortConfigOutput)
}

// TemplatePortConfigArrayInput is an input type that accepts TemplatePortConfigArray and TemplatePortConfigArrayOutput values.
// You can construct a concrete instance of `TemplatePortConfigArrayInput` via:
//
//	TemplatePortConfigArray{ TemplatePortConfigArgs{...} }
type TemplatePortConfigArrayInput interface {
	pulumi.Input

	ToTemplatePortConfigArrayOutput() TemplatePortConfigArrayOutput
	ToTemplatePortConfigArrayOutputWithContext(context.Context) TemplatePortConfigArrayOutput
}

type TemplatePortConfigArray []TemplatePortConfigInput

func (TemplatePortConfigArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]TemplatePortConfig)(nil)).Elem()
}

func (i TemplatePortConfigArray) ToTemplatePortConfigArrayOutput() TemplatePortConfigArrayOutput {
	return i.ToTemplatePortConfigArrayOutputWithContext(context.Background())
}

func (i TemplatePortConfigArray) ToTemplatePortConfigArrayOutputWithContext(ctx context.Context) TemplatePortConfigArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TemplatePortConfigArrayOutput)
}

type TemplatePortConfigOutput struct{ *pulumi.OutputState }

func (TemplatePortConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*TemplatePortConfig)(nil)).Elem()
}

func (o TemplatePortConfigOutput) ToTemplatePortConfigOutput() TemplatePortConfigOutput {
	return o
}

func (o TemplatePortConfigOutput) ToTemplatePortConfigOutputWithContext(ctx context.Context) TemplatePortConfigOutput {
	return o
}

func (o TemplatePortConfigOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v TemplatePortConfig) *string { return v.Name }).(pulumi.StringPtrOutput)
}

func (o TemplatePortConfigOutput) Port() pulumi.StringOutput {
	return o.ApplyT(func(v TemplatePortConfig) string { return v.Port }).(pulumi.StringOutput)
}

type TemplatePortConfigArrayOutput struct{ *pulumi.OutputState }

func (TemplatePortConfigArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]TemplatePortConfig)(nil)).Elem()
}

func (o TemplatePortConfigArrayOutput) ToTemplatePortConfigArrayOutput() TemplatePortConfigArrayOutput {
	return o
}

func (o TemplatePortConfigArrayOutput) ToTemplatePortConfigArrayOutputWithContext(ctx context.Context) TemplatePortConfigArrayOutput {
	return o
}

func (o TemplatePortConfigArrayOutput) Index(i pulumi.IntInput) TemplatePortConfigOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) TemplatePortConfig {
		return vs[0].([]TemplatePortConfig)[vs[1].(int)]
	}).(TemplatePortConfigOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SavingsPlanInput)(nil)).Elem(), SavingsPlanArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*SavingsPlanPtrInput)(nil)).Elem(), SavingsPlanArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*TemplatePortConfigInput)(nil)).Elem(), TemplatePortConfigArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*TemplatePortConfigArrayInput)(nil)).Elem(), TemplatePortConfigArray{})
	pulumi.RegisterOutputType(CPUFlavorOutputOutput{})
	pulumi.RegisterOutputType(CPUFlavorOutputArrayOutput{})
	pulumi.RegisterOutputType(DataCenterOutputOutput{})
	pulumi.RegisterOutputType(DataCenterOutputArrayOutput{})
	pulumi.RegisterOutputType(EndpointNetworkVolumeBindingOutput{})
	pulumi.RegisterOutputType(EndpointNetworkVolumeBindingArrayOutput{})
	pulumi.RegisterOutputType(GpuAvailabilityItemOutput{})
	pulumi.RegisterOutputType(GpuAvailabilityItemArrayOutput{})
	pulumi.RegisterOutputType(GpuTypeOutputOutput{})
	pulumi.RegisterOutputType(GpuTypeOutputArrayOutput{})
	pulumi.RegisterOutputType(LowestPriceOutputOutput{})
	pulumi.RegisterOutputType(LowestPriceOutputPtrOutput{})
	pulumi.RegisterOutputType(SavingsPlanOutput{})
	pulumi.RegisterOutputType(SavingsPlanPtrOutput{})
	pulumi.RegisterOutputType(TemplatePortConfigOutput{})
	pulumi.RegisterOutputType(TemplatePortConfigArrayOutput{})
}
