// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.runpod.runpod.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetCPUFlavorsArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetCPUFlavorsArgs Empty = new GetCPUFlavorsArgs();

    /**
     * Filter by serverless eligibility.
     * 
     */
    @Import(name="isSls")
    private @Nullable Output<Boolean> isSls;

    /**
     * @return Filter by serverless eligibility.
     * 
     */
    public Optional<Output<Boolean>> isSls() {
        return Optional.ofNullable(this.isSls);
    }

    /**
     * When true, return only serverless-eligible CPU flavors.
     * 
     */
    @Import(name="slsOnly")
    private @Nullable Output<Boolean> slsOnly;

    /**
     * @return When true, return only serverless-eligible CPU flavors.
     * 
     */
    public Optional<Output<Boolean>> slsOnly() {
        return Optional.ofNullable(this.slsOnly);
    }

    private GetCPUFlavorsArgs() {}

    private GetCPUFlavorsArgs(GetCPUFlavorsArgs $) {
        this.isSls = $.isSls;
        this.slsOnly = $.slsOnly;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetCPUFlavorsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetCPUFlavorsArgs $;

        public Builder() {
            $ = new GetCPUFlavorsArgs();
        }

        public Builder(GetCPUFlavorsArgs defaults) {
            $ = new GetCPUFlavorsArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param isSls Filter by serverless eligibility.
         * 
         * @return builder
         * 
         */
        public Builder isSls(@Nullable Output<Boolean> isSls) {
            $.isSls = isSls;
            return this;
        }

        /**
         * @param isSls Filter by serverless eligibility.
         * 
         * @return builder
         * 
         */
        public Builder isSls(Boolean isSls) {
            return isSls(Output.of(isSls));
        }

        /**
         * @param slsOnly When true, return only serverless-eligible CPU flavors.
         * 
         * @return builder
         * 
         */
        public Builder slsOnly(@Nullable Output<Boolean> slsOnly) {
            $.slsOnly = slsOnly;
            return this;
        }

        /**
         * @param slsOnly When true, return only serverless-eligible CPU flavors.
         * 
         * @return builder
         * 
         */
        public Builder slsOnly(Boolean slsOnly) {
            return slsOnly(Output.of(slsOnly));
        }

        public GetCPUFlavorsArgs build() {
            return $;
        }
    }

}
