// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.runpod.runpod.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetCpuFlavorsPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetCpuFlavorsPlainArgs Empty = new GetCpuFlavorsPlainArgs();

    /**
     * Filter by serverless eligibility.
     * 
     */
    @Import(name="isSls")
    private @Nullable Boolean isSls;

    /**
     * @return Filter by serverless eligibility.
     * 
     */
    public Optional<Boolean> isSls() {
        return Optional.ofNullable(this.isSls);
    }

    /**
     * When true, return only serverless-eligible CPU flavors.
     * 
     */
    @Import(name="slsOnly")
    private @Nullable Boolean slsOnly;

    /**
     * @return When true, return only serverless-eligible CPU flavors.
     * 
     */
    public Optional<Boolean> slsOnly() {
        return Optional.ofNullable(this.slsOnly);
    }

    private GetCpuFlavorsPlainArgs() {}

    private GetCpuFlavorsPlainArgs(GetCpuFlavorsPlainArgs $) {
        this.isSls = $.isSls;
        this.slsOnly = $.slsOnly;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetCpuFlavorsPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetCpuFlavorsPlainArgs $;

        public Builder() {
            $ = new GetCpuFlavorsPlainArgs();
        }

        public Builder(GetCpuFlavorsPlainArgs defaults) {
            $ = new GetCpuFlavorsPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param isSls Filter by serverless eligibility.
         * 
         * @return builder
         * 
         */
        public Builder isSls(@Nullable Boolean isSls) {
            $.isSls = isSls;
            return this;
        }

        /**
         * @param slsOnly When true, return only serverless-eligible CPU flavors.
         * 
         * @return builder
         * 
         */
        public Builder slsOnly(@Nullable Boolean slsOnly) {
            $.slsOnly = slsOnly;
            return this;
        }

        public GetCpuFlavorsPlainArgs build() {
            return $;
        }
    }

}
