// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.runpod.runpod.inputs;




public final class GetGpuTypesArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetGpuTypesArgs Empty = new GetGpuTypesArgs();

    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private GetGpuTypesArgs $;

        public Builder() {
            $ = new GetGpuTypesArgs();
        }
        public GetGpuTypesArgs build() {
            return $;
        }
    }

}
