// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.runpod.runpod.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Double;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SavingsPlanArgs extends com.pulumi.resources.ResourceArgs {

    public static final SavingsPlanArgs Empty = new SavingsPlanArgs();

    @Import(name="planLength")
    private @Nullable Output<String> planLength;

    public Optional<Output<String>> planLength() {
        return Optional.ofNullable(this.planLength);
    }

    @Import(name="upfrontCost")
    private @Nullable Output<Double> upfrontCost;

    public Optional<Output<Double>> upfrontCost() {
        return Optional.ofNullable(this.upfrontCost);
    }

    private SavingsPlanArgs() {}

    private SavingsPlanArgs(SavingsPlanArgs $) {
        this.planLength = $.planLength;
        this.upfrontCost = $.upfrontCost;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SavingsPlanArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SavingsPlanArgs $;

        public Builder() {
            $ = new SavingsPlanArgs();
        }

        public Builder(SavingsPlanArgs defaults) {
            $ = new SavingsPlanArgs(Objects.requireNonNull(defaults));
        }

        public Builder planLength(@Nullable Output<String> planLength) {
            $.planLength = planLength;
            return this;
        }

        public Builder planLength(String planLength) {
            return planLength(Output.of(planLength));
        }

        public Builder upfrontCost(@Nullable Output<Double> upfrontCost) {
            $.upfrontCost = upfrontCost;
            return this;
        }

        public Builder upfrontCost(Double upfrontCost) {
            return upfrontCost(Output.of(upfrontCost));
        }

        public SavingsPlanArgs build() {
            return $;
        }
    }

}
