# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .container_registry_auth import *
from .endpoint import *
from .get_gpu_types import *
from .network_volume import *
from .pod import *
from .provider import *
from .secret import *
from .template import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_runpod.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_runpod.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "runpod",
  "mod": "index",
  "fqn": "pulumi_runpod",
  "classes": {
   "runpod:index:ContainerRegistryAuth": "ContainerRegistryAuth",
   "runpod:index:Endpoint": "Endpoint",
   "runpod:index:NetworkVolume": "NetworkVolume",
   "runpod:index:Pod": "Pod",
   "runpod:index:Secret": "Secret",
   "runpod:index:Template": "Template"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "runpod",
  "token": "pulumi:providers:runpod",
  "fqn": "pulumi_runpod",
  "class": "Provider"
 }
]
"""
)
