# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'SavingsPlanArgs',
    'SavingsPlanArgsDict',
]

MYPY = False

if not MYPY:
    class SavingsPlanArgsDict(TypedDict):
        plan_length: NotRequired[pulumi.Input[builtins.str]]
        upfront_cost: NotRequired[pulumi.Input[builtins.float]]
elif False:
    SavingsPlanArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class SavingsPlanArgs:
    def __init__(__self__, *,
                 plan_length: Optional[pulumi.Input[builtins.str]] = None,
                 upfront_cost: Optional[pulumi.Input[builtins.float]] = None):
        if plan_length is not None:
            pulumi.set(__self__, "plan_length", plan_length)
        if upfront_cost is not None:
            pulumi.set(__self__, "upfront_cost", upfront_cost)

    @property
    @pulumi.getter(name="planLength")
    def plan_length(self) -> Optional[pulumi.Input[builtins.str]]:
        return pulumi.get(self, "plan_length")

    @plan_length.setter
    def plan_length(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "plan_length", value)

    @property
    @pulumi.getter(name="upfrontCost")
    def upfront_cost(self) -> Optional[pulumi.Input[builtins.float]]:
        return pulumi.get(self, "upfront_cost")

    @upfront_cost.setter
    def upfront_cost(self, value: Optional[pulumi.Input[builtins.float]]):
        pulumi.set(self, "upfront_cost", value)


