# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['EndpointArgs', 'Endpoint']

@pulumi.input_type
class EndpointArgs:
    def __init__(__self__, *,
                 name: pulumi.Input[_builtins.str],
                 allowed_cuda_versions: Optional[pulumi.Input[_builtins.str]] = None,
                 bind_endpoint: Optional[pulumi.Input[_builtins.bool]] = None,
                 env: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 execution_timeout_ms: Optional[pulumi.Input[_builtins.int]] = None,
                 flash_boot_type: Optional[pulumi.Input[_builtins.str]] = None,
                 flash_environment_id: Optional[pulumi.Input[_builtins.str]] = None,
                 gpu_count: Optional[pulumi.Input[_builtins.int]] = None,
                 gpu_ids: Optional[pulumi.Input[_builtins.str]] = None,
                 hub_release_id: Optional[pulumi.Input[_builtins.str]] = None,
                 idle_timeout: Optional[pulumi.Input[_builtins.int]] = None,
                 instance_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 locations: Optional[pulumi.Input[_builtins.str]] = None,
                 min_cuda_version: Optional[pulumi.Input[_builtins.str]] = None,
                 model_name: Optional[pulumi.Input[_builtins.str]] = None,
                 model_references: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 network_volume_id: Optional[pulumi.Input[_builtins.str]] = None,
                 scaler_type: Optional[pulumi.Input[_builtins.str]] = None,
                 scaler_value: Optional[pulumi.Input[_builtins.int]] = None,
                 template_id: Optional[pulumi.Input[_builtins.str]] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None,
                 workers_max: Optional[pulumi.Input[_builtins.int]] = None,
                 workers_min: Optional[pulumi.Input[_builtins.int]] = None):
        """
        The set of arguments for constructing a Endpoint resource.
        :param pulumi.Input[_builtins.str] name: A name for the endpoint.
        :param pulumi.Input[_builtins.str] allowed_cuda_versions: Comma-separated list of allowed CUDA versions.
        :param pulumi.Input[_builtins.bool] bind_endpoint: Whether to bind the endpoint to specific workers.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] env: Environment variables as key-value pairs.
        :param pulumi.Input[_builtins.int] execution_timeout_ms: Maximum execution time in milliseconds before a request is terminated.
        :param pulumi.Input[_builtins.str] flash_boot_type: The flash boot type.
        :param pulumi.Input[_builtins.str] flash_environment_id: The flash environment ID.
        :param pulumi.Input[_builtins.int] gpu_count: The number of GPUs per worker.
        :param pulumi.Input[_builtins.str] gpu_ids: The GPU type IDs to use (e.g. "AMPERE_16").
        :param pulumi.Input[_builtins.str] hub_release_id: The hub release ID for the endpoint.
        :param pulumi.Input[_builtins.int] idle_timeout: The number of seconds a worker can remain idle before being scaled down.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] instance_ids: Specific instance IDs to use for workers.
        :param pulumi.Input[_builtins.str] locations: Comma-separated data center locations for worker deployment.
        :param pulumi.Input[_builtins.str] min_cuda_version: The minimum CUDA version required.
        :param pulumi.Input[_builtins.str] model_name: The model name for the endpoint.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] model_references: Model references for the endpoint.
        :param pulumi.Input[_builtins.str] network_volume_id: The network volume ID to attach to endpoint workers.
        :param pulumi.Input[_builtins.str] scaler_type: The autoscaler type (e.g. "QUEUE_DELAY", "REQUEST_COUNT").
        :param pulumi.Input[_builtins.int] scaler_value: The autoscaler target value.
        :param pulumi.Input[_builtins.str] template_id: The template ID to use for the endpoint workers.
        :param pulumi.Input[_builtins.str] type: The endpoint type.
        :param pulumi.Input[_builtins.int] workers_max: The maximum number of workers to scale up to.
        :param pulumi.Input[_builtins.int] workers_min: The minimum number of workers to keep running.
        """
        pulumi.set(__self__, "name", name)
        if allowed_cuda_versions is not None:
            pulumi.set(__self__, "allowed_cuda_versions", allowed_cuda_versions)
        if bind_endpoint is not None:
            pulumi.set(__self__, "bind_endpoint", bind_endpoint)
        if env is not None:
            pulumi.set(__self__, "env", env)
        if execution_timeout_ms is not None:
            pulumi.set(__self__, "execution_timeout_ms", execution_timeout_ms)
        if flash_boot_type is not None:
            pulumi.set(__self__, "flash_boot_type", flash_boot_type)
        if flash_environment_id is not None:
            pulumi.set(__self__, "flash_environment_id", flash_environment_id)
        if gpu_count is not None:
            pulumi.set(__self__, "gpu_count", gpu_count)
        if gpu_ids is not None:
            pulumi.set(__self__, "gpu_ids", gpu_ids)
        if hub_release_id is not None:
            pulumi.set(__self__, "hub_release_id", hub_release_id)
        if idle_timeout is not None:
            pulumi.set(__self__, "idle_timeout", idle_timeout)
        if instance_ids is not None:
            pulumi.set(__self__, "instance_ids", instance_ids)
        if locations is not None:
            pulumi.set(__self__, "locations", locations)
        if min_cuda_version is not None:
            pulumi.set(__self__, "min_cuda_version", min_cuda_version)
        if model_name is not None:
            pulumi.set(__self__, "model_name", model_name)
        if model_references is not None:
            pulumi.set(__self__, "model_references", model_references)
        if network_volume_id is not None:
            pulumi.set(__self__, "network_volume_id", network_volume_id)
        if scaler_type is not None:
            pulumi.set(__self__, "scaler_type", scaler_type)
        if scaler_value is not None:
            pulumi.set(__self__, "scaler_value", scaler_value)
        if template_id is not None:
            pulumi.set(__self__, "template_id", template_id)
        if type is not None:
            pulumi.set(__self__, "type", type)
        if workers_max is not None:
            pulumi.set(__self__, "workers_max", workers_max)
        if workers_min is not None:
            pulumi.set(__self__, "workers_min", workers_min)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str]:
        """
        A name for the endpoint.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="allowedCudaVersions")
    def allowed_cuda_versions(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Comma-separated list of allowed CUDA versions.
        """
        return pulumi.get(self, "allowed_cuda_versions")

    @allowed_cuda_versions.setter
    def allowed_cuda_versions(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "allowed_cuda_versions", value)

    @_builtins.property
    @pulumi.getter(name="bindEndpoint")
    def bind_endpoint(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether to bind the endpoint to specific workers.
        """
        return pulumi.get(self, "bind_endpoint")

    @bind_endpoint.setter
    def bind_endpoint(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "bind_endpoint", value)

    @_builtins.property
    @pulumi.getter
    def env(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Environment variables as key-value pairs.
        """
        return pulumi.get(self, "env")

    @env.setter
    def env(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "env", value)

    @_builtins.property
    @pulumi.getter(name="executionTimeoutMs")
    def execution_timeout_ms(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Maximum execution time in milliseconds before a request is terminated.
        """
        return pulumi.get(self, "execution_timeout_ms")

    @execution_timeout_ms.setter
    def execution_timeout_ms(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "execution_timeout_ms", value)

    @_builtins.property
    @pulumi.getter(name="flashBootType")
    def flash_boot_type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The flash boot type.
        """
        return pulumi.get(self, "flash_boot_type")

    @flash_boot_type.setter
    def flash_boot_type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "flash_boot_type", value)

    @_builtins.property
    @pulumi.getter(name="flashEnvironmentId")
    def flash_environment_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The flash environment ID.
        """
        return pulumi.get(self, "flash_environment_id")

    @flash_environment_id.setter
    def flash_environment_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "flash_environment_id", value)

    @_builtins.property
    @pulumi.getter(name="gpuCount")
    def gpu_count(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        The number of GPUs per worker.
        """
        return pulumi.get(self, "gpu_count")

    @gpu_count.setter
    def gpu_count(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "gpu_count", value)

    @_builtins.property
    @pulumi.getter(name="gpuIds")
    def gpu_ids(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The GPU type IDs to use (e.g. "AMPERE_16").
        """
        return pulumi.get(self, "gpu_ids")

    @gpu_ids.setter
    def gpu_ids(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "gpu_ids", value)

    @_builtins.property
    @pulumi.getter(name="hubReleaseId")
    def hub_release_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The hub release ID for the endpoint.
        """
        return pulumi.get(self, "hub_release_id")

    @hub_release_id.setter
    def hub_release_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "hub_release_id", value)

    @_builtins.property
    @pulumi.getter(name="idleTimeout")
    def idle_timeout(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        The number of seconds a worker can remain idle before being scaled down.
        """
        return pulumi.get(self, "idle_timeout")

    @idle_timeout.setter
    def idle_timeout(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "idle_timeout", value)

    @_builtins.property
    @pulumi.getter(name="instanceIds")
    def instance_ids(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Specific instance IDs to use for workers.
        """
        return pulumi.get(self, "instance_ids")

    @instance_ids.setter
    def instance_ids(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "instance_ids", value)

    @_builtins.property
    @pulumi.getter
    def locations(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Comma-separated data center locations for worker deployment.
        """
        return pulumi.get(self, "locations")

    @locations.setter
    def locations(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "locations", value)

    @_builtins.property
    @pulumi.getter(name="minCudaVersion")
    def min_cuda_version(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The minimum CUDA version required.
        """
        return pulumi.get(self, "min_cuda_version")

    @min_cuda_version.setter
    def min_cuda_version(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "min_cuda_version", value)

    @_builtins.property
    @pulumi.getter(name="modelName")
    def model_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The model name for the endpoint.
        """
        return pulumi.get(self, "model_name")

    @model_name.setter
    def model_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "model_name", value)

    @_builtins.property
    @pulumi.getter(name="modelReferences")
    def model_references(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Model references for the endpoint.
        """
        return pulumi.get(self, "model_references")

    @model_references.setter
    def model_references(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "model_references", value)

    @_builtins.property
    @pulumi.getter(name="networkVolumeId")
    def network_volume_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The network volume ID to attach to endpoint workers.
        """
        return pulumi.get(self, "network_volume_id")

    @network_volume_id.setter
    def network_volume_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "network_volume_id", value)

    @_builtins.property
    @pulumi.getter(name="scalerType")
    def scaler_type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The autoscaler type (e.g. "QUEUE_DELAY", "REQUEST_COUNT").
        """
        return pulumi.get(self, "scaler_type")

    @scaler_type.setter
    def scaler_type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "scaler_type", value)

    @_builtins.property
    @pulumi.getter(name="scalerValue")
    def scaler_value(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        The autoscaler target value.
        """
        return pulumi.get(self, "scaler_value")

    @scaler_value.setter
    def scaler_value(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "scaler_value", value)

    @_builtins.property
    @pulumi.getter(name="templateId")
    def template_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The template ID to use for the endpoint workers.
        """
        return pulumi.get(self, "template_id")

    @template_id.setter
    def template_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "template_id", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The endpoint type.
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "type", value)

    @_builtins.property
    @pulumi.getter(name="workersMax")
    def workers_max(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        The maximum number of workers to scale up to.
        """
        return pulumi.get(self, "workers_max")

    @workers_max.setter
    def workers_max(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "workers_max", value)

    @_builtins.property
    @pulumi.getter(name="workersMin")
    def workers_min(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        The minimum number of workers to keep running.
        """
        return pulumi.get(self, "workers_min")

    @workers_min.setter
    def workers_min(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "workers_min", value)


@pulumi.type_token("runpod:index:Endpoint")
class Endpoint(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 allowed_cuda_versions: Optional[pulumi.Input[_builtins.str]] = None,
                 bind_endpoint: Optional[pulumi.Input[_builtins.bool]] = None,
                 env: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 execution_timeout_ms: Optional[pulumi.Input[_builtins.int]] = None,
                 flash_boot_type: Optional[pulumi.Input[_builtins.str]] = None,
                 flash_environment_id: Optional[pulumi.Input[_builtins.str]] = None,
                 gpu_count: Optional[pulumi.Input[_builtins.int]] = None,
                 gpu_ids: Optional[pulumi.Input[_builtins.str]] = None,
                 hub_release_id: Optional[pulumi.Input[_builtins.str]] = None,
                 idle_timeout: Optional[pulumi.Input[_builtins.int]] = None,
                 instance_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 locations: Optional[pulumi.Input[_builtins.str]] = None,
                 min_cuda_version: Optional[pulumi.Input[_builtins.str]] = None,
                 model_name: Optional[pulumi.Input[_builtins.str]] = None,
                 model_references: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 network_volume_id: Optional[pulumi.Input[_builtins.str]] = None,
                 scaler_type: Optional[pulumi.Input[_builtins.str]] = None,
                 scaler_value: Optional[pulumi.Input[_builtins.int]] = None,
                 template_id: Optional[pulumi.Input[_builtins.str]] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None,
                 workers_max: Optional[pulumi.Input[_builtins.int]] = None,
                 workers_min: Optional[pulumi.Input[_builtins.int]] = None,
                 __props__=None):
        """
        Create a Endpoint resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] allowed_cuda_versions: Comma-separated list of allowed CUDA versions.
        :param pulumi.Input[_builtins.bool] bind_endpoint: Whether to bind the endpoint to specific workers.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] env: Environment variables as key-value pairs.
        :param pulumi.Input[_builtins.int] execution_timeout_ms: Maximum execution time in milliseconds before a request is terminated.
        :param pulumi.Input[_builtins.str] flash_boot_type: The flash boot type.
        :param pulumi.Input[_builtins.str] flash_environment_id: The flash environment ID.
        :param pulumi.Input[_builtins.int] gpu_count: The number of GPUs per worker.
        :param pulumi.Input[_builtins.str] gpu_ids: The GPU type IDs to use (e.g. "AMPERE_16").
        :param pulumi.Input[_builtins.str] hub_release_id: The hub release ID for the endpoint.
        :param pulumi.Input[_builtins.int] idle_timeout: The number of seconds a worker can remain idle before being scaled down.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] instance_ids: Specific instance IDs to use for workers.
        :param pulumi.Input[_builtins.str] locations: Comma-separated data center locations for worker deployment.
        :param pulumi.Input[_builtins.str] min_cuda_version: The minimum CUDA version required.
        :param pulumi.Input[_builtins.str] model_name: The model name for the endpoint.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] model_references: Model references for the endpoint.
        :param pulumi.Input[_builtins.str] name: A name for the endpoint.
        :param pulumi.Input[_builtins.str] network_volume_id: The network volume ID to attach to endpoint workers.
        :param pulumi.Input[_builtins.str] scaler_type: The autoscaler type (e.g. "QUEUE_DELAY", "REQUEST_COUNT").
        :param pulumi.Input[_builtins.int] scaler_value: The autoscaler target value.
        :param pulumi.Input[_builtins.str] template_id: The template ID to use for the endpoint workers.
        :param pulumi.Input[_builtins.str] type: The endpoint type.
        :param pulumi.Input[_builtins.int] workers_max: The maximum number of workers to scale up to.
        :param pulumi.Input[_builtins.int] workers_min: The minimum number of workers to keep running.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: EndpointArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Endpoint resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param EndpointArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(EndpointArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 allowed_cuda_versions: Optional[pulumi.Input[_builtins.str]] = None,
                 bind_endpoint: Optional[pulumi.Input[_builtins.bool]] = None,
                 env: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 execution_timeout_ms: Optional[pulumi.Input[_builtins.int]] = None,
                 flash_boot_type: Optional[pulumi.Input[_builtins.str]] = None,
                 flash_environment_id: Optional[pulumi.Input[_builtins.str]] = None,
                 gpu_count: Optional[pulumi.Input[_builtins.int]] = None,
                 gpu_ids: Optional[pulumi.Input[_builtins.str]] = None,
                 hub_release_id: Optional[pulumi.Input[_builtins.str]] = None,
                 idle_timeout: Optional[pulumi.Input[_builtins.int]] = None,
                 instance_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 locations: Optional[pulumi.Input[_builtins.str]] = None,
                 min_cuda_version: Optional[pulumi.Input[_builtins.str]] = None,
                 model_name: Optional[pulumi.Input[_builtins.str]] = None,
                 model_references: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 network_volume_id: Optional[pulumi.Input[_builtins.str]] = None,
                 scaler_type: Optional[pulumi.Input[_builtins.str]] = None,
                 scaler_value: Optional[pulumi.Input[_builtins.int]] = None,
                 template_id: Optional[pulumi.Input[_builtins.str]] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None,
                 workers_max: Optional[pulumi.Input[_builtins.int]] = None,
                 workers_min: Optional[pulumi.Input[_builtins.int]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = EndpointArgs.__new__(EndpointArgs)

            __props__.__dict__["allowed_cuda_versions"] = allowed_cuda_versions
            __props__.__dict__["bind_endpoint"] = bind_endpoint
            __props__.__dict__["env"] = env
            __props__.__dict__["execution_timeout_ms"] = execution_timeout_ms
            __props__.__dict__["flash_boot_type"] = flash_boot_type
            __props__.__dict__["flash_environment_id"] = flash_environment_id
            __props__.__dict__["gpu_count"] = gpu_count
            __props__.__dict__["gpu_ids"] = gpu_ids
            __props__.__dict__["hub_release_id"] = hub_release_id
            __props__.__dict__["idle_timeout"] = idle_timeout
            __props__.__dict__["instance_ids"] = instance_ids
            __props__.__dict__["locations"] = locations
            __props__.__dict__["min_cuda_version"] = min_cuda_version
            __props__.__dict__["model_name"] = model_name
            __props__.__dict__["model_references"] = model_references
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            __props__.__dict__["network_volume_id"] = network_volume_id
            __props__.__dict__["scaler_type"] = scaler_type
            __props__.__dict__["scaler_value"] = scaler_value
            __props__.__dict__["template_id"] = template_id
            __props__.__dict__["type"] = type
            __props__.__dict__["workers_max"] = workers_max
            __props__.__dict__["workers_min"] = workers_min
            __props__.__dict__["endpoint_id"] = None
        super(Endpoint, __self__).__init__(
            'runpod:index:Endpoint',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'Endpoint':
        """
        Get an existing Endpoint resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = EndpointArgs.__new__(EndpointArgs)

        __props__.__dict__["allowed_cuda_versions"] = None
        __props__.__dict__["bind_endpoint"] = None
        __props__.__dict__["endpoint_id"] = None
        __props__.__dict__["env"] = None
        __props__.__dict__["execution_timeout_ms"] = None
        __props__.__dict__["flash_boot_type"] = None
        __props__.__dict__["flash_environment_id"] = None
        __props__.__dict__["gpu_count"] = None
        __props__.__dict__["gpu_ids"] = None
        __props__.__dict__["hub_release_id"] = None
        __props__.__dict__["idle_timeout"] = None
        __props__.__dict__["instance_ids"] = None
        __props__.__dict__["locations"] = None
        __props__.__dict__["min_cuda_version"] = None
        __props__.__dict__["model_name"] = None
        __props__.__dict__["model_references"] = None
        __props__.__dict__["name"] = None
        __props__.__dict__["network_volume_id"] = None
        __props__.__dict__["scaler_type"] = None
        __props__.__dict__["scaler_value"] = None
        __props__.__dict__["template_id"] = None
        __props__.__dict__["type"] = None
        __props__.__dict__["workers_max"] = None
        __props__.__dict__["workers_min"] = None
        return Endpoint(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="allowedCudaVersions")
    def allowed_cuda_versions(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Comma-separated list of allowed CUDA versions.
        """
        return pulumi.get(self, "allowed_cuda_versions")

    @_builtins.property
    @pulumi.getter(name="bindEndpoint")
    def bind_endpoint(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether to bind the endpoint to specific workers.
        """
        return pulumi.get(self, "bind_endpoint")

    @_builtins.property
    @pulumi.getter(name="endpointId")
    def endpoint_id(self) -> pulumi.Output[_builtins.str]:
        """
        The unique identifier of the endpoint.
        """
        return pulumi.get(self, "endpoint_id")

    @_builtins.property
    @pulumi.getter
    def env(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        """
        Environment variables as key-value pairs.
        """
        return pulumi.get(self, "env")

    @_builtins.property
    @pulumi.getter(name="executionTimeoutMs")
    def execution_timeout_ms(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Maximum execution time in milliseconds before a request is terminated.
        """
        return pulumi.get(self, "execution_timeout_ms")

    @_builtins.property
    @pulumi.getter(name="flashBootType")
    def flash_boot_type(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The flash boot type.
        """
        return pulumi.get(self, "flash_boot_type")

    @_builtins.property
    @pulumi.getter(name="flashEnvironmentId")
    def flash_environment_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The flash environment ID.
        """
        return pulumi.get(self, "flash_environment_id")

    @_builtins.property
    @pulumi.getter(name="gpuCount")
    def gpu_count(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        The number of GPUs per worker.
        """
        return pulumi.get(self, "gpu_count")

    @_builtins.property
    @pulumi.getter(name="gpuIds")
    def gpu_ids(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The GPU type IDs to use (e.g. "AMPERE_16").
        """
        return pulumi.get(self, "gpu_ids")

    @_builtins.property
    @pulumi.getter(name="hubReleaseId")
    def hub_release_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The hub release ID for the endpoint.
        """
        return pulumi.get(self, "hub_release_id")

    @_builtins.property
    @pulumi.getter(name="idleTimeout")
    def idle_timeout(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        The number of seconds a worker can remain idle before being scaled down.
        """
        return pulumi.get(self, "idle_timeout")

    @_builtins.property
    @pulumi.getter(name="instanceIds")
    def instance_ids(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Specific instance IDs to use for workers.
        """
        return pulumi.get(self, "instance_ids")

    @_builtins.property
    @pulumi.getter
    def locations(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Comma-separated data center locations for worker deployment.
        """
        return pulumi.get(self, "locations")

    @_builtins.property
    @pulumi.getter(name="minCudaVersion")
    def min_cuda_version(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The minimum CUDA version required.
        """
        return pulumi.get(self, "min_cuda_version")

    @_builtins.property
    @pulumi.getter(name="modelName")
    def model_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The model name for the endpoint.
        """
        return pulumi.get(self, "model_name")

    @_builtins.property
    @pulumi.getter(name="modelReferences")
    def model_references(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Model references for the endpoint.
        """
        return pulumi.get(self, "model_references")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        A name for the endpoint.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="networkVolumeId")
    def network_volume_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The network volume ID to attach to endpoint workers.
        """
        return pulumi.get(self, "network_volume_id")

    @_builtins.property
    @pulumi.getter(name="scalerType")
    def scaler_type(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The autoscaler type (e.g. "QUEUE_DELAY", "REQUEST_COUNT").
        """
        return pulumi.get(self, "scaler_type")

    @_builtins.property
    @pulumi.getter(name="scalerValue")
    def scaler_value(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        The autoscaler target value.
        """
        return pulumi.get(self, "scaler_value")

    @_builtins.property
    @pulumi.getter(name="templateId")
    def template_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The template ID to use for the endpoint workers.
        """
        return pulumi.get(self, "template_id")

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The endpoint type.
        """
        return pulumi.get(self, "type")

    @_builtins.property
    @pulumi.getter(name="workersMax")
    def workers_max(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        The maximum number of workers to scale up to.
        """
        return pulumi.get(self, "workers_max")

    @_builtins.property
    @pulumi.getter(name="workersMin")
    def workers_min(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        The minimum number of workers to keep running.
        """
        return pulumi.get(self, "workers_min")

