# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetGpuTypesResult',
    'AwaitableGetGpuTypesResult',
    'get_gpu_types',
    'get_gpu_types_output',
]

@pulumi.output_type
class GetGpuTypesResult:
    def __init__(__self__, gpu_types=None):
        if gpu_types and not isinstance(gpu_types, list):
            raise TypeError("Expected argument 'gpu_types' to be a list")
        pulumi.set(__self__, "gpu_types", gpu_types)

    @property
    @pulumi.getter(name="gpuTypes")
    def gpu_types(self) -> Sequence['outputs.GpuTypeOutput']:
        """
        The list of available GPU types.
        """
        return pulumi.get(self, "gpu_types")


class AwaitableGetGpuTypesResult(GetGpuTypesResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetGpuTypesResult(
            gpu_types=self.gpu_types)


def get_gpu_types(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetGpuTypesResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('runpod:index:getGpuTypes', __args__, opts=opts, typ=GetGpuTypesResult).value

    return AwaitableGetGpuTypesResult(
        gpu_types=pulumi.get(__ret__, 'gpu_types'))
def get_gpu_types_output(opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetGpuTypesResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('runpod:index:getGpuTypes', __args__, opts=opts, typ=GetGpuTypesResult)
    return __ret__.apply(lambda __response__: GetGpuTypesResult(
        gpu_types=pulumi.get(__response__, 'gpu_types')))
