# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetCpuFlavorsResult',
    'AwaitableGetCpuFlavorsResult',
    'get_cpu_flavors',
    'get_cpu_flavors_output',
]

@pulumi.output_type
class GetCpuFlavorsResult:
    def __init__(__self__, cpu_flavors=None):
        if cpu_flavors and not isinstance(cpu_flavors, list):
            raise TypeError("Expected argument 'cpu_flavors' to be a list")
        pulumi.set(__self__, "cpu_flavors", cpu_flavors)

    @property
    @pulumi.getter(name="cpuFlavors")
    def cpu_flavors(self) -> Sequence['outputs.CpuFlavorOutput']:
        """
        The list of available CPU instance flavors.
        """
        return pulumi.get(self, "cpu_flavors")


class AwaitableGetCpuFlavorsResult(GetCpuFlavorsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetCpuFlavorsResult(
            cpu_flavors=self.cpu_flavors)


def get_cpu_flavors(is_sls: Optional[builtins.bool] = None,
                    sls_only: Optional[builtins.bool] = None,
                    opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetCpuFlavorsResult:
    """
    Use this data source to access information about an existing resource.

    :param builtins.bool is_sls: Filter by serverless eligibility.
    :param builtins.bool sls_only: When true, return only serverless-eligible CPU flavors.
    """
    __args__ = dict()
    __args__['isSls'] = is_sls
    __args__['slsOnly'] = sls_only
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('runpod:index:getCpuFlavors', __args__, opts=opts, typ=GetCpuFlavorsResult).value

    return AwaitableGetCpuFlavorsResult(
        cpu_flavors=pulumi.get(__ret__, 'cpu_flavors'))
def get_cpu_flavors_output(is_sls: Optional[pulumi.Input[Optional[builtins.bool]]] = None,
                           sls_only: Optional[pulumi.Input[Optional[builtins.bool]]] = None,
                           opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetCpuFlavorsResult]:
    """
    Use this data source to access information about an existing resource.

    :param builtins.bool is_sls: Filter by serverless eligibility.
    :param builtins.bool sls_only: When true, return only serverless-eligible CPU flavors.
    """
    __args__ = dict()
    __args__['isSls'] = is_sls
    __args__['slsOnly'] = sls_only
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('runpod:index:getCpuFlavors', __args__, opts=opts, typ=GetCpuFlavorsResult)
    return __ret__.apply(lambda __response__: GetCpuFlavorsResult(
        cpu_flavors=pulumi.get(__response__, 'cpu_flavors')))
