# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GpuTypeOutput',
    'SavingsPlan',
]

@pulumi.output_type
class GpuTypeOutput(dict):
    def __init__(__self__, *,
                 community_cloud: builtins.bool,
                 community_price: builtins.float,
                 display_name: builtins.str,
                 id: builtins.str,
                 max_gpu_count: builtins.int,
                 memory_in_gb: builtins.int,
                 secure_cloud: builtins.bool,
                 secure_price: builtins.float):
        pulumi.set(__self__, "community_cloud", community_cloud)
        pulumi.set(__self__, "community_price", community_price)
        pulumi.set(__self__, "display_name", display_name)
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "max_gpu_count", max_gpu_count)
        pulumi.set(__self__, "memory_in_gb", memory_in_gb)
        pulumi.set(__self__, "secure_cloud", secure_cloud)
        pulumi.set(__self__, "secure_price", secure_price)

    @property
    @pulumi.getter(name="communityCloud")
    def community_cloud(self) -> builtins.bool:
        return pulumi.get(self, "community_cloud")

    @property
    @pulumi.getter(name="communityPrice")
    def community_price(self) -> builtins.float:
        return pulumi.get(self, "community_price")

    @property
    @pulumi.getter(name="displayName")
    def display_name(self) -> builtins.str:
        return pulumi.get(self, "display_name")

    @property
    @pulumi.getter
    def id(self) -> builtins.str:
        return pulumi.get(self, "id")

    @property
    @pulumi.getter(name="maxGpuCount")
    def max_gpu_count(self) -> builtins.int:
        return pulumi.get(self, "max_gpu_count")

    @property
    @pulumi.getter(name="memoryInGb")
    def memory_in_gb(self) -> builtins.int:
        return pulumi.get(self, "memory_in_gb")

    @property
    @pulumi.getter(name="secureCloud")
    def secure_cloud(self) -> builtins.bool:
        return pulumi.get(self, "secure_cloud")

    @property
    @pulumi.getter(name="securePrice")
    def secure_price(self) -> builtins.float:
        return pulumi.get(self, "secure_price")


@pulumi.output_type
class SavingsPlan(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "planLength":
            suggest = "plan_length"
        elif key == "upfrontCost":
            suggest = "upfront_cost"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in SavingsPlan. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        SavingsPlan.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        SavingsPlan.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 plan_length: Optional[builtins.str] = None,
                 upfront_cost: Optional[builtins.float] = None):
        if plan_length is not None:
            pulumi.set(__self__, "plan_length", plan_length)
        if upfront_cost is not None:
            pulumi.set(__self__, "upfront_cost", upfront_cost)

    @property
    @pulumi.getter(name="planLength")
    def plan_length(self) -> Optional[builtins.str]:
        return pulumi.get(self, "plan_length")

    @property
    @pulumi.getter(name="upfrontCost")
    def upfront_cost(self) -> Optional[builtins.float]:
        return pulumi.get(self, "upfront_cost")


