# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'CPUFlavorOutput',
    'DataCenterOutput',
    'EndpointNetworkVolumeBinding',
    'GpuAvailabilityItem',
    'GpuTypeOutput',
    'LowestPriceOutput',
    'SavingsPlan',
    'TemplatePortConfig',
]

@pulumi.output_type
class CPUFlavorOutput(dict):
    def __init__(__self__, *,
                 disk_limit_per_vcpu: _builtins.int,
                 display_name: _builtins.str,
                 group_id: _builtins.str,
                 group_name: _builtins.str,
                 id: _builtins.str,
                 max_vcpu: _builtins.int,
                 min_vcpu: _builtins.float,
                 ram_multiplier: _builtins.float,
                 vcpu_burstable: _builtins.bool):
        """
        :param _builtins.int disk_limit_per_vcpu: Disk limit per vCPU (in GB).
        :param _builtins.str display_name: The human-readable name of the CPU flavor.
        :param _builtins.str group_id: The group this flavor belongs to.
        :param _builtins.str group_name: The display name of the flavor group.
        :param _builtins.str id: The unique identifier of the CPU flavor (used as flavorId in instanceId).
        :param _builtins.int max_vcpu: The maximum number of vCPUs for this flavor.
        :param _builtins.float min_vcpu: The minimum number of vCPUs for this flavor.
        :param _builtins.float ram_multiplier: RAM allocated per vCPU (in GB).
        :param _builtins.bool vcpu_burstable: Whether vCPUs are burstable.
        """
        pulumi.set(__self__, "disk_limit_per_vcpu", disk_limit_per_vcpu)
        pulumi.set(__self__, "display_name", display_name)
        pulumi.set(__self__, "group_id", group_id)
        pulumi.set(__self__, "group_name", group_name)
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "max_vcpu", max_vcpu)
        pulumi.set(__self__, "min_vcpu", min_vcpu)
        pulumi.set(__self__, "ram_multiplier", ram_multiplier)
        pulumi.set(__self__, "vcpu_burstable", vcpu_burstable)

    @_builtins.property
    @pulumi.getter(name="diskLimitPerVcpu")
    def disk_limit_per_vcpu(self) -> _builtins.int:
        """
        Disk limit per vCPU (in GB).
        """
        return pulumi.get(self, "disk_limit_per_vcpu")

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> _builtins.str:
        """
        The human-readable name of the CPU flavor.
        """
        return pulumi.get(self, "display_name")

    @_builtins.property
    @pulumi.getter(name="groupId")
    def group_id(self) -> _builtins.str:
        """
        The group this flavor belongs to.
        """
        return pulumi.get(self, "group_id")

    @_builtins.property
    @pulumi.getter(name="groupName")
    def group_name(self) -> _builtins.str:
        """
        The display name of the flavor group.
        """
        return pulumi.get(self, "group_name")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The unique identifier of the CPU flavor (used as flavorId in instanceId).
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="maxVcpu")
    def max_vcpu(self) -> _builtins.int:
        """
        The maximum number of vCPUs for this flavor.
        """
        return pulumi.get(self, "max_vcpu")

    @_builtins.property
    @pulumi.getter(name="minVcpu")
    def min_vcpu(self) -> _builtins.float:
        """
        The minimum number of vCPUs for this flavor.
        """
        return pulumi.get(self, "min_vcpu")

    @_builtins.property
    @pulumi.getter(name="ramMultiplier")
    def ram_multiplier(self) -> _builtins.float:
        """
        RAM allocated per vCPU (in GB).
        """
        return pulumi.get(self, "ram_multiplier")

    @_builtins.property
    @pulumi.getter(name="vcpuBurstable")
    def vcpu_burstable(self) -> _builtins.bool:
        """
        Whether vCPUs are burstable.
        """
        return pulumi.get(self, "vcpu_burstable")


@pulumi.output_type
class DataCenterOutput(dict):
    def __init__(__self__, *,
                 compliance: Sequence[_builtins.str],
                 global_network: _builtins.bool,
                 gpu_availability: Sequence['outputs.GpuAvailabilityItem'],
                 id: _builtins.str,
                 listed: _builtins.bool,
                 location: _builtins.str,
                 name: _builtins.str,
                 region: _builtins.str,
                 storage_support: _builtins.bool):
        """
        :param Sequence[_builtins.str] compliance: Compliance certifications held by this data center.
        :param _builtins.bool global_network: Whether this data center is part of the global network.
        :param Sequence['GpuAvailabilityItem'] gpu_availability: GPU availability within this data center.
        :param _builtins.str id: The unique identifier of the data center (used as dataCenterId).
        :param _builtins.bool listed: Whether this data center is publicly listed.
        :param _builtins.str location: The geographic location of the data center.
        :param _builtins.str name: The display name of the data center.
        :param _builtins.str region: The broad region (e.g. NORTH_AMERICA, EUROPE).
        :param _builtins.bool storage_support: Whether this data center supports network volumes.
        """
        pulumi.set(__self__, "compliance", compliance)
        pulumi.set(__self__, "global_network", global_network)
        pulumi.set(__self__, "gpu_availability", gpu_availability)
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "listed", listed)
        pulumi.set(__self__, "location", location)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "region", region)
        pulumi.set(__self__, "storage_support", storage_support)

    @_builtins.property
    @pulumi.getter
    def compliance(self) -> Sequence[_builtins.str]:
        """
        Compliance certifications held by this data center.
        """
        return pulumi.get(self, "compliance")

    @_builtins.property
    @pulumi.getter(name="globalNetwork")
    def global_network(self) -> _builtins.bool:
        """
        Whether this data center is part of the global network.
        """
        return pulumi.get(self, "global_network")

    @_builtins.property
    @pulumi.getter(name="gpuAvailability")
    def gpu_availability(self) -> Sequence['outputs.GpuAvailabilityItem']:
        """
        GPU availability within this data center.
        """
        return pulumi.get(self, "gpu_availability")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The unique identifier of the data center (used as dataCenterId).
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def listed(self) -> _builtins.bool:
        """
        Whether this data center is publicly listed.
        """
        return pulumi.get(self, "listed")

    @_builtins.property
    @pulumi.getter
    def location(self) -> _builtins.str:
        """
        The geographic location of the data center.
        """
        return pulumi.get(self, "location")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The display name of the data center.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def region(self) -> _builtins.str:
        """
        The broad region (e.g. NORTH_AMERICA, EUROPE).
        """
        return pulumi.get(self, "region")

    @_builtins.property
    @pulumi.getter(name="storageSupport")
    def storage_support(self) -> _builtins.bool:
        """
        Whether this data center supports network volumes.
        """
        return pulumi.get(self, "storage_support")


@pulumi.output_type
class EndpointNetworkVolumeBinding(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "dataCenterId":
            suggest = "data_center_id"
        elif key == "networkVolumeId":
            suggest = "network_volume_id"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in EndpointNetworkVolumeBinding. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        EndpointNetworkVolumeBinding.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        EndpointNetworkVolumeBinding.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 data_center_id: _builtins.str,
                 network_volume_id: _builtins.str):
        pulumi.set(__self__, "data_center_id", data_center_id)
        pulumi.set(__self__, "network_volume_id", network_volume_id)

    @_builtins.property
    @pulumi.getter(name="dataCenterId")
    def data_center_id(self) -> _builtins.str:
        return pulumi.get(self, "data_center_id")

    @_builtins.property
    @pulumi.getter(name="networkVolumeId")
    def network_volume_id(self) -> _builtins.str:
        return pulumi.get(self, "network_volume_id")


@pulumi.output_type
class GpuAvailabilityItem(dict):
    def __init__(__self__, *,
                 available: _builtins.bool,
                 gpu_type_display_name: _builtins.str,
                 gpu_type_id: _builtins.str,
                 stock_status: _builtins.str):
        """
        :param _builtins.bool available: Whether this GPU type is currently available at this data center.
        :param _builtins.str gpu_type_display_name: The human-readable GPU type name.
        :param _builtins.str gpu_type_id: The GPU type identifier.
        :param _builtins.str stock_status: Current stock status (e.g. High, Medium, Low).
        """
        pulumi.set(__self__, "available", available)
        pulumi.set(__self__, "gpu_type_display_name", gpu_type_display_name)
        pulumi.set(__self__, "gpu_type_id", gpu_type_id)
        pulumi.set(__self__, "stock_status", stock_status)

    @_builtins.property
    @pulumi.getter
    def available(self) -> _builtins.bool:
        """
        Whether this GPU type is currently available at this data center.
        """
        return pulumi.get(self, "available")

    @_builtins.property
    @pulumi.getter(name="gpuTypeDisplayName")
    def gpu_type_display_name(self) -> _builtins.str:
        """
        The human-readable GPU type name.
        """
        return pulumi.get(self, "gpu_type_display_name")

    @_builtins.property
    @pulumi.getter(name="gpuTypeId")
    def gpu_type_id(self) -> _builtins.str:
        """
        The GPU type identifier.
        """
        return pulumi.get(self, "gpu_type_id")

    @_builtins.property
    @pulumi.getter(name="stockStatus")
    def stock_status(self) -> _builtins.str:
        """
        Current stock status (e.g. High, Medium, Low).
        """
        return pulumi.get(self, "stock_status")


@pulumi.output_type
class GpuTypeOutput(dict):
    def __init__(__self__, *,
                 community_cloud: _builtins.bool,
                 community_price: _builtins.float,
                 display_name: _builtins.str,
                 id: _builtins.str,
                 max_gpu_count: _builtins.int,
                 memory_in_gb: _builtins.int,
                 secure_cloud: _builtins.bool,
                 secure_price: _builtins.float,
                 lowest_price: Optional['outputs.LowestPriceOutput'] = None):
        """
        :param _builtins.bool community_cloud: Whether the GPU is available in community cloud.
        :param _builtins.float community_price: The price per hour in community cloud (USD).
        :param _builtins.str display_name: The display name of the GPU type.
        :param _builtins.str id: The unique identifier of the GPU type.
        :param _builtins.int max_gpu_count: The maximum number of this GPU type that can be allocated.
        :param _builtins.int memory_in_gb: The amount of VRAM in GB.
        :param _builtins.bool secure_cloud: Whether the GPU is available in secure cloud.
        :param _builtins.float secure_price: The price per hour in secure cloud (USD).
        """
        pulumi.set(__self__, "community_cloud", community_cloud)
        pulumi.set(__self__, "community_price", community_price)
        pulumi.set(__self__, "display_name", display_name)
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "max_gpu_count", max_gpu_count)
        pulumi.set(__self__, "memory_in_gb", memory_in_gb)
        pulumi.set(__self__, "secure_cloud", secure_cloud)
        pulumi.set(__self__, "secure_price", secure_price)
        if lowest_price is not None:
            pulumi.set(__self__, "lowest_price", lowest_price)

    @_builtins.property
    @pulumi.getter(name="communityCloud")
    def community_cloud(self) -> _builtins.bool:
        """
        Whether the GPU is available in community cloud.
        """
        return pulumi.get(self, "community_cloud")

    @_builtins.property
    @pulumi.getter(name="communityPrice")
    def community_price(self) -> _builtins.float:
        """
        The price per hour in community cloud (USD).
        """
        return pulumi.get(self, "community_price")

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> _builtins.str:
        """
        The display name of the GPU type.
        """
        return pulumi.get(self, "display_name")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The unique identifier of the GPU type.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="maxGpuCount")
    def max_gpu_count(self) -> _builtins.int:
        """
        The maximum number of this GPU type that can be allocated.
        """
        return pulumi.get(self, "max_gpu_count")

    @_builtins.property
    @pulumi.getter(name="memoryInGb")
    def memory_in_gb(self) -> _builtins.int:
        """
        The amount of VRAM in GB.
        """
        return pulumi.get(self, "memory_in_gb")

    @_builtins.property
    @pulumi.getter(name="secureCloud")
    def secure_cloud(self) -> _builtins.bool:
        """
        Whether the GPU is available in secure cloud.
        """
        return pulumi.get(self, "secure_cloud")

    @_builtins.property
    @pulumi.getter(name="securePrice")
    def secure_price(self) -> _builtins.float:
        """
        The price per hour in secure cloud (USD).
        """
        return pulumi.get(self, "secure_price")

    @_builtins.property
    @pulumi.getter(name="lowestPrice")
    def lowest_price(self) -> Optional['outputs.LowestPriceOutput']:
        return pulumi.get(self, "lowest_price")


@pulumi.output_type
class LowestPriceOutput(dict):
    def __init__(__self__, *,
                 minimum_bid_price: _builtins.float,
                 rented_count: _builtins.int,
                 stock_status: _builtins.str,
                 total_count: _builtins.int,
                 uninterruptable_price: _builtins.float):
        pulumi.set(__self__, "minimum_bid_price", minimum_bid_price)
        pulumi.set(__self__, "rented_count", rented_count)
        pulumi.set(__self__, "stock_status", stock_status)
        pulumi.set(__self__, "total_count", total_count)
        pulumi.set(__self__, "uninterruptable_price", uninterruptable_price)

    @_builtins.property
    @pulumi.getter(name="minimumBidPrice")
    def minimum_bid_price(self) -> _builtins.float:
        return pulumi.get(self, "minimum_bid_price")

    @_builtins.property
    @pulumi.getter(name="rentedCount")
    def rented_count(self) -> _builtins.int:
        return pulumi.get(self, "rented_count")

    @_builtins.property
    @pulumi.getter(name="stockStatus")
    def stock_status(self) -> _builtins.str:
        return pulumi.get(self, "stock_status")

    @_builtins.property
    @pulumi.getter(name="totalCount")
    def total_count(self) -> _builtins.int:
        return pulumi.get(self, "total_count")

    @_builtins.property
    @pulumi.getter(name="uninterruptablePrice")
    def uninterruptable_price(self) -> _builtins.float:
        return pulumi.get(self, "uninterruptable_price")


@pulumi.output_type
class SavingsPlan(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "planLength":
            suggest = "plan_length"
        elif key == "upfrontCost":
            suggest = "upfront_cost"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in SavingsPlan. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        SavingsPlan.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        SavingsPlan.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 plan_length: Optional[_builtins.str] = None,
                 upfront_cost: Optional[_builtins.float] = None):
        """
        :param _builtins.str plan_length: The length of the savings plan.
        :param _builtins.float upfront_cost: The upfront cost for the savings plan.
        """
        if plan_length is not None:
            pulumi.set(__self__, "plan_length", plan_length)
        if upfront_cost is not None:
            pulumi.set(__self__, "upfront_cost", upfront_cost)

    @_builtins.property
    @pulumi.getter(name="planLength")
    def plan_length(self) -> Optional[_builtins.str]:
        """
        The length of the savings plan.
        """
        return pulumi.get(self, "plan_length")

    @_builtins.property
    @pulumi.getter(name="upfrontCost")
    def upfront_cost(self) -> Optional[_builtins.float]:
        """
        The upfront cost for the savings plan.
        """
        return pulumi.get(self, "upfront_cost")


@pulumi.output_type
class TemplatePortConfig(dict):
    def __init__(__self__, *,
                 port: _builtins.str,
                 name: Optional[_builtins.str] = None):
        pulumi.set(__self__, "port", port)
        if name is not None:
            pulumi.set(__self__, "name", name)

    @_builtins.property
    @pulumi.getter
    def port(self) -> _builtins.str:
        return pulumi.get(self, "port")

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "name")


