// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Runpod.Outputs
{

    [OutputType]
    public sealed class CPUAvailabilityItem
    {
        /// <summary>
        /// Whether this CPU flavor is currently available at this data center.
        /// </summary>
        public readonly bool Available;
        /// <summary>
        /// The CPU flavor identifier.
        /// </summary>
        public readonly string CpuFlavorId;
        /// <summary>
        /// The human-readable CPU flavor name.
        /// </summary>
        public readonly string DisplayName;
        /// <summary>
        /// The CPU availability identifier.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Current stock status (e.g. High, Medium, Low).
        /// </summary>
        public readonly string StockStatus;

        [OutputConstructor]
        private CPUAvailabilityItem(
            bool available,

            string cpuFlavorId,

            string displayName,

            string id,

            string stockStatus)
        {
            Available = available;
            CpuFlavorId = cpuFlavorId;
            DisplayName = displayName;
            Id = id;
            StockStatus = stockStatus;
        }
    }
}
