// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Runpod.Outputs
{

    [OutputType]
    public sealed class GpuTypeOutput
    {
        public readonly bool CommunityCloud;
        public readonly double CommunityPrice;
        public readonly string DisplayName;
        public readonly string Id;
        public readonly int MaxGpuCount;
        public readonly int MemoryInGb;
        public readonly bool SecureCloud;
        public readonly double SecurePrice;

        [OutputConstructor]
        private GpuTypeOutput(
            bool communityCloud,

            double communityPrice,

            string displayName,

            string id,

            int maxGpuCount,

            int memoryInGb,

            bool secureCloud,

            double securePrice)
        {
            CommunityCloud = communityCloud;
            CommunityPrice = communityPrice;
            DisplayName = displayName;
            Id = id;
            MaxGpuCount = maxGpuCount;
            MemoryInGb = memoryInGb;
            SecureCloud = secureCloud;
            SecurePrice = securePrice;
        }
    }
}
