// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Runpod.Outputs
{

    [OutputType]
    public sealed class TemplatePortConfig
    {
        public readonly string? Name;
        public readonly string Port;

        [OutputConstructor]
        private TemplatePortConfig(
            string? name,

            string port)
        {
            Name = name;
            Port = port;
        }
    }
}
