// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.runpod.runpod.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.runpod.runpod.outputs.DataCenterOutput;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetDataCentersResult {
    /**
     * @return The list of available RunPod data centers.
     * 
     */
    private List<DataCenterOutput> dataCenters;

    private GetDataCentersResult() {}
    /**
     * @return The list of available RunPod data centers.
     * 
     */
    public List<DataCenterOutput> dataCenters() {
        return this.dataCenters;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetDataCentersResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<DataCenterOutput> dataCenters;
        public Builder() {}
        public Builder(GetDataCentersResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.dataCenters = defaults.dataCenters;
        }

        @CustomType.Setter
        public Builder dataCenters(List<DataCenterOutput> dataCenters) {
            if (dataCenters == null) {
              throw new MissingRequiredPropertyException("GetDataCentersResult", "dataCenters");
            }
            this.dataCenters = dataCenters;
            return this;
        }
        public Builder dataCenters(DataCenterOutput... dataCenters) {
            return dataCenters(List.of(dataCenters));
        }
        public GetDataCentersResult build() {
            final var _resultValue = new GetDataCentersResult();
            _resultValue.dataCenters = dataCenters;
            return _resultValue;
        }
    }
}
