// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.runpod.runpod.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GpuAvailabilityItem {
    /**
     * @return Whether this GPU type is currently available at this data center.
     * 
     */
    private Boolean available;
    /**
     * @return The human-readable GPU type name.
     * 
     */
    private String gpuTypeDisplayName;
    /**
     * @return The GPU type identifier.
     * 
     */
    private String gpuTypeId;
    /**
     * @return Current stock status (e.g. High, Medium, Low).
     * 
     */
    private String stockStatus;

    private GpuAvailabilityItem() {}
    /**
     * @return Whether this GPU type is currently available at this data center.
     * 
     */
    public Boolean available() {
        return this.available;
    }
    /**
     * @return The human-readable GPU type name.
     * 
     */
    public String gpuTypeDisplayName() {
        return this.gpuTypeDisplayName;
    }
    /**
     * @return The GPU type identifier.
     * 
     */
    public String gpuTypeId() {
        return this.gpuTypeId;
    }
    /**
     * @return Current stock status (e.g. High, Medium, Low).
     * 
     */
    public String stockStatus() {
        return this.stockStatus;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GpuAvailabilityItem defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Boolean available;
        private String gpuTypeDisplayName;
        private String gpuTypeId;
        private String stockStatus;
        public Builder() {}
        public Builder(GpuAvailabilityItem defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.available = defaults.available;
    	      this.gpuTypeDisplayName = defaults.gpuTypeDisplayName;
    	      this.gpuTypeId = defaults.gpuTypeId;
    	      this.stockStatus = defaults.stockStatus;
        }

        @CustomType.Setter
        public Builder available(Boolean available) {
            if (available == null) {
              throw new MissingRequiredPropertyException("GpuAvailabilityItem", "available");
            }
            this.available = available;
            return this;
        }
        @CustomType.Setter
        public Builder gpuTypeDisplayName(String gpuTypeDisplayName) {
            if (gpuTypeDisplayName == null) {
              throw new MissingRequiredPropertyException("GpuAvailabilityItem", "gpuTypeDisplayName");
            }
            this.gpuTypeDisplayName = gpuTypeDisplayName;
            return this;
        }
        @CustomType.Setter
        public Builder gpuTypeId(String gpuTypeId) {
            if (gpuTypeId == null) {
              throw new MissingRequiredPropertyException("GpuAvailabilityItem", "gpuTypeId");
            }
            this.gpuTypeId = gpuTypeId;
            return this;
        }
        @CustomType.Setter
        public Builder stockStatus(String stockStatus) {
            if (stockStatus == null) {
              throw new MissingRequiredPropertyException("GpuAvailabilityItem", "stockStatus");
            }
            this.stockStatus = stockStatus;
            return this;
        }
        public GpuAvailabilityItem build() {
            final var _resultValue = new GpuAvailabilityItem();
            _resultValue.available = available;
            _resultValue.gpuTypeDisplayName = gpuTypeDisplayName;
            _resultValue.gpuTypeId = gpuTypeId;
            _resultValue.stockStatus = stockStatus;
            return _resultValue;
        }
    }
}
