// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.runpod.runpod.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GpuTypeOutput {
    private Boolean communityCloud;
    private Double communityPrice;
    private String displayName;
    private String id;
    private Integer maxGpuCount;
    private Integer memoryInGb;
    private Boolean secureCloud;
    private Double securePrice;

    private GpuTypeOutput() {}
    public Boolean communityCloud() {
        return this.communityCloud;
    }
    public Double communityPrice() {
        return this.communityPrice;
    }
    public String displayName() {
        return this.displayName;
    }
    public String id() {
        return this.id;
    }
    public Integer maxGpuCount() {
        return this.maxGpuCount;
    }
    public Integer memoryInGb() {
        return this.memoryInGb;
    }
    public Boolean secureCloud() {
        return this.secureCloud;
    }
    public Double securePrice() {
        return this.securePrice;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GpuTypeOutput defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Boolean communityCloud;
        private Double communityPrice;
        private String displayName;
        private String id;
        private Integer maxGpuCount;
        private Integer memoryInGb;
        private Boolean secureCloud;
        private Double securePrice;
        public Builder() {}
        public Builder(GpuTypeOutput defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.communityCloud = defaults.communityCloud;
    	      this.communityPrice = defaults.communityPrice;
    	      this.displayName = defaults.displayName;
    	      this.id = defaults.id;
    	      this.maxGpuCount = defaults.maxGpuCount;
    	      this.memoryInGb = defaults.memoryInGb;
    	      this.secureCloud = defaults.secureCloud;
    	      this.securePrice = defaults.securePrice;
        }

        @CustomType.Setter
        public Builder communityCloud(Boolean communityCloud) {
            if (communityCloud == null) {
              throw new MissingRequiredPropertyException("GpuTypeOutput", "communityCloud");
            }
            this.communityCloud = communityCloud;
            return this;
        }
        @CustomType.Setter
        public Builder communityPrice(Double communityPrice) {
            if (communityPrice == null) {
              throw new MissingRequiredPropertyException("GpuTypeOutput", "communityPrice");
            }
            this.communityPrice = communityPrice;
            return this;
        }
        @CustomType.Setter
        public Builder displayName(String displayName) {
            if (displayName == null) {
              throw new MissingRequiredPropertyException("GpuTypeOutput", "displayName");
            }
            this.displayName = displayName;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GpuTypeOutput", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder maxGpuCount(Integer maxGpuCount) {
            if (maxGpuCount == null) {
              throw new MissingRequiredPropertyException("GpuTypeOutput", "maxGpuCount");
            }
            this.maxGpuCount = maxGpuCount;
            return this;
        }
        @CustomType.Setter
        public Builder memoryInGb(Integer memoryInGb) {
            if (memoryInGb == null) {
              throw new MissingRequiredPropertyException("GpuTypeOutput", "memoryInGb");
            }
            this.memoryInGb = memoryInGb;
            return this;
        }
        @CustomType.Setter
        public Builder secureCloud(Boolean secureCloud) {
            if (secureCloud == null) {
              throw new MissingRequiredPropertyException("GpuTypeOutput", "secureCloud");
            }
            this.secureCloud = secureCloud;
            return this;
        }
        @CustomType.Setter
        public Builder securePrice(Double securePrice) {
            if (securePrice == null) {
              throw new MissingRequiredPropertyException("GpuTypeOutput", "securePrice");
            }
            this.securePrice = securePrice;
            return this;
        }
        public GpuTypeOutput build() {
            final var _resultValue = new GpuTypeOutput();
            _resultValue.communityCloud = communityCloud;
            _resultValue.communityPrice = communityPrice;
            _resultValue.displayName = displayName;
            _resultValue.id = id;
            _resultValue.maxGpuCount = maxGpuCount;
            _resultValue.memoryInGb = memoryInGb;
            _resultValue.secureCloud = secureCloud;
            _resultValue.securePrice = securePrice;
            return _resultValue;
        }
    }
}
