// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.runpod.runpod.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.runpod.runpod.outputs.LowestPriceOutput;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GpuTypeOutput {
    /**
     * @return Whether the GPU is available in community cloud.
     * 
     */
    private Boolean communityCloud;
    /**
     * @return The price per hour in community cloud (USD).
     * 
     */
    private Double communityPrice;
    /**
     * @return The display name of the GPU type.
     * 
     */
    private String displayName;
    /**
     * @return The unique identifier of the GPU type.
     * 
     */
    private String id;
    private @Nullable LowestPriceOutput lowestPrice;
    /**
     * @return The maximum number of this GPU type that can be allocated.
     * 
     */
    private Integer maxGpuCount;
    /**
     * @return The amount of VRAM in GB.
     * 
     */
    private Integer memoryInGb;
    /**
     * @return Whether the GPU is available in secure cloud.
     * 
     */
    private Boolean secureCloud;
    /**
     * @return The price per hour in secure cloud (USD).
     * 
     */
    private Double securePrice;

    private GpuTypeOutput() {}
    /**
     * @return Whether the GPU is available in community cloud.
     * 
     */
    public Boolean communityCloud() {
        return this.communityCloud;
    }
    /**
     * @return The price per hour in community cloud (USD).
     * 
     */
    public Double communityPrice() {
        return this.communityPrice;
    }
    /**
     * @return The display name of the GPU type.
     * 
     */
    public String displayName() {
        return this.displayName;
    }
    /**
     * @return The unique identifier of the GPU type.
     * 
     */
    public String id() {
        return this.id;
    }
    public Optional<LowestPriceOutput> lowestPrice() {
        return Optional.ofNullable(this.lowestPrice);
    }
    /**
     * @return The maximum number of this GPU type that can be allocated.
     * 
     */
    public Integer maxGpuCount() {
        return this.maxGpuCount;
    }
    /**
     * @return The amount of VRAM in GB.
     * 
     */
    public Integer memoryInGb() {
        return this.memoryInGb;
    }
    /**
     * @return Whether the GPU is available in secure cloud.
     * 
     */
    public Boolean secureCloud() {
        return this.secureCloud;
    }
    /**
     * @return The price per hour in secure cloud (USD).
     * 
     */
    public Double securePrice() {
        return this.securePrice;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GpuTypeOutput defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Boolean communityCloud;
        private Double communityPrice;
        private String displayName;
        private String id;
        private @Nullable LowestPriceOutput lowestPrice;
        private Integer maxGpuCount;
        private Integer memoryInGb;
        private Boolean secureCloud;
        private Double securePrice;
        public Builder() {}
        public Builder(GpuTypeOutput defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.communityCloud = defaults.communityCloud;
    	      this.communityPrice = defaults.communityPrice;
    	      this.displayName = defaults.displayName;
    	      this.id = defaults.id;
    	      this.lowestPrice = defaults.lowestPrice;
    	      this.maxGpuCount = defaults.maxGpuCount;
    	      this.memoryInGb = defaults.memoryInGb;
    	      this.secureCloud = defaults.secureCloud;
    	      this.securePrice = defaults.securePrice;
        }

        @CustomType.Setter
        public Builder communityCloud(Boolean communityCloud) {
            if (communityCloud == null) {
              throw new MissingRequiredPropertyException("GpuTypeOutput", "communityCloud");
            }
            this.communityCloud = communityCloud;
            return this;
        }
        @CustomType.Setter
        public Builder communityPrice(Double communityPrice) {
            if (communityPrice == null) {
              throw new MissingRequiredPropertyException("GpuTypeOutput", "communityPrice");
            }
            this.communityPrice = communityPrice;
            return this;
        }
        @CustomType.Setter
        public Builder displayName(String displayName) {
            if (displayName == null) {
              throw new MissingRequiredPropertyException("GpuTypeOutput", "displayName");
            }
            this.displayName = displayName;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GpuTypeOutput", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder lowestPrice(@Nullable LowestPriceOutput lowestPrice) {

            this.lowestPrice = lowestPrice;
            return this;
        }
        @CustomType.Setter
        public Builder maxGpuCount(Integer maxGpuCount) {
            if (maxGpuCount == null) {
              throw new MissingRequiredPropertyException("GpuTypeOutput", "maxGpuCount");
            }
            this.maxGpuCount = maxGpuCount;
            return this;
        }
        @CustomType.Setter
        public Builder memoryInGb(Integer memoryInGb) {
            if (memoryInGb == null) {
              throw new MissingRequiredPropertyException("GpuTypeOutput", "memoryInGb");
            }
            this.memoryInGb = memoryInGb;
            return this;
        }
        @CustomType.Setter
        public Builder secureCloud(Boolean secureCloud) {
            if (secureCloud == null) {
              throw new MissingRequiredPropertyException("GpuTypeOutput", "secureCloud");
            }
            this.secureCloud = secureCloud;
            return this;
        }
        @CustomType.Setter
        public Builder securePrice(Double securePrice) {
            if (securePrice == null) {
              throw new MissingRequiredPropertyException("GpuTypeOutput", "securePrice");
            }
            this.securePrice = securePrice;
            return this;
        }
        public GpuTypeOutput build() {
            final var _resultValue = new GpuTypeOutput();
            _resultValue.communityCloud = communityCloud;
            _resultValue.communityPrice = communityPrice;
            _resultValue.displayName = displayName;
            _resultValue.id = id;
            _resultValue.lowestPrice = lowestPrice;
            _resultValue.maxGpuCount = maxGpuCount;
            _resultValue.memoryInGb = memoryInGb;
            _resultValue.secureCloud = secureCloud;
            _resultValue.securePrice = securePrice;
            return _resultValue;
        }
    }
}
