// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.runpod.runpod;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.runpod.runpod.NetworkVolumeArgs;
import com.runpod.runpod.Utilities;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="runpod:index:NetworkVolume")
public class NetworkVolume extends com.pulumi.resources.CustomResource {
    @Export(name="dataCenterId", refs={String.class}, tree="[0]")
    private Output<String> dataCenterId;

    public Output<String> dataCenterId() {
        return this.dataCenterId;
    }
    @Export(name="isNextGenStorage", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> isNextGenStorage;

    public Output<Optional<Boolean>> isNextGenStorage() {
        return Codegen.optional(this.isNextGenStorage);
    }
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    public Output<String> name() {
        return this.name;
    }
    @Export(name="networkVolumeId", refs={String.class}, tree="[0]")
    private Output<String> networkVolumeId;

    public Output<String> networkVolumeId() {
        return this.networkVolumeId;
    }
    @Export(name="size", refs={Integer.class}, tree="[0]")
    private Output<Integer> size;

    public Output<Integer> size() {
        return this.size;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public NetworkVolume(java.lang.String name) {
        this(name, NetworkVolumeArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public NetworkVolume(java.lang.String name, NetworkVolumeArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public NetworkVolume(java.lang.String name, NetworkVolumeArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("runpod:index:NetworkVolume", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private NetworkVolume(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("runpod:index:NetworkVolume", name, null, makeResourceOptions(options, id), false);
    }

    private static NetworkVolumeArgs makeArgs(NetworkVolumeArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? NetworkVolumeArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/runpod/pulumi-runpod")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static NetworkVolume get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new NetworkVolume(name, id, options);
    }
}
