// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.runpod.runpod;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class NetworkVolumeArgs extends com.pulumi.resources.ResourceArgs {

    public static final NetworkVolumeArgs Empty = new NetworkVolumeArgs();

    @Import(name="dataCenterId", required=true)
    private Output<String> dataCenterId;

    public Output<String> dataCenterId() {
        return this.dataCenterId;
    }

    @Import(name="isNextGenStorage")
    private @Nullable Output<Boolean> isNextGenStorage;

    public Optional<Output<Boolean>> isNextGenStorage() {
        return Optional.ofNullable(this.isNextGenStorage);
    }

    @Import(name="name", required=true)
    private Output<String> name;

    public Output<String> name() {
        return this.name;
    }

    @Import(name="size", required=true)
    private Output<Integer> size;

    public Output<Integer> size() {
        return this.size;
    }

    private NetworkVolumeArgs() {}

    private NetworkVolumeArgs(NetworkVolumeArgs $) {
        this.dataCenterId = $.dataCenterId;
        this.isNextGenStorage = $.isNextGenStorage;
        this.name = $.name;
        this.size = $.size;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(NetworkVolumeArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private NetworkVolumeArgs $;

        public Builder() {
            $ = new NetworkVolumeArgs();
        }

        public Builder(NetworkVolumeArgs defaults) {
            $ = new NetworkVolumeArgs(Objects.requireNonNull(defaults));
        }

        public Builder dataCenterId(Output<String> dataCenterId) {
            $.dataCenterId = dataCenterId;
            return this;
        }

        public Builder dataCenterId(String dataCenterId) {
            return dataCenterId(Output.of(dataCenterId));
        }

        public Builder isNextGenStorage(@Nullable Output<Boolean> isNextGenStorage) {
            $.isNextGenStorage = isNextGenStorage;
            return this;
        }

        public Builder isNextGenStorage(Boolean isNextGenStorage) {
            return isNextGenStorage(Output.of(isNextGenStorage));
        }

        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public Builder size(Output<Integer> size) {
            $.size = size;
            return this;
        }

        public Builder size(Integer size) {
            return size(Output.of(size));
        }

        public NetworkVolumeArgs build() {
            if ($.dataCenterId == null) {
                throw new MissingRequiredPropertyException("NetworkVolumeArgs", "dataCenterId");
            }
            if ($.name == null) {
                throw new MissingRequiredPropertyException("NetworkVolumeArgs", "name");
            }
            if ($.size == null) {
                throw new MissingRequiredPropertyException("NetworkVolumeArgs", "size");
            }
            return $;
        }
    }

}
