// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.runpod.runpod;

import com.pulumi.core.Output;
import com.pulumi.core.TypeShape;
import com.pulumi.deployment.Deployment;
import com.pulumi.deployment.InvokeOptions;
import com.pulumi.deployment.InvokeOutputOptions;
import com.runpod.runpod.Utilities;
import com.runpod.runpod.inputs.GetGpuTypesArgs;
import com.runpod.runpod.inputs.GetGpuTypesPlainArgs;
import com.runpod.runpod.outputs.GetGpuTypesResult;
import java.util.concurrent.CompletableFuture;

public final class RunpodFunctions {
    public static Output<GetGpuTypesResult> getGpuTypes() {
        return getGpuTypes(GetGpuTypesArgs.Empty, InvokeOptions.Empty);
    }
    public static CompletableFuture<GetGpuTypesResult> getGpuTypesPlain() {
        return getGpuTypesPlain(GetGpuTypesPlainArgs.Empty, InvokeOptions.Empty);
    }
    public static Output<GetGpuTypesResult> getGpuTypes(GetGpuTypesArgs args) {
        return getGpuTypes(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<GetGpuTypesResult> getGpuTypesPlain(GetGpuTypesPlainArgs args) {
        return getGpuTypesPlain(args, InvokeOptions.Empty);
    }
    public static Output<GetGpuTypesResult> getGpuTypes(GetGpuTypesArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("runpod:index:getGpuTypes", TypeShape.of(GetGpuTypesResult.class), args, Utilities.withVersion(options));
    }
    public static Output<GetGpuTypesResult> getGpuTypes(GetGpuTypesArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("runpod:index:getGpuTypes", TypeShape.of(GetGpuTypesResult.class), args, Utilities.withVersion(options));
    }
    public static CompletableFuture<GetGpuTypesResult> getGpuTypesPlain(GetGpuTypesPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("runpod:index:getGpuTypes", TypeShape.of(GetGpuTypesResult.class), args, Utilities.withVersion(options));
    }
}
