// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.runpod.runpod;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.runpod.runpod.TemplateArgs;
import com.runpod.runpod.Utilities;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="runpod:index:Template")
public class Template extends com.pulumi.resources.CustomResource {
    @Export(name="advancedStart", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> advancedStart;

    public Output<Optional<Boolean>> advancedStart() {
        return Codegen.optional(this.advancedStart);
    }
    @Export(name="category", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> category;

    public Output<Optional<String>> category() {
        return Codegen.optional(this.category);
    }
    @Export(name="containerDiskInGb", refs={Integer.class}, tree="[0]")
    private Output<Integer> containerDiskInGb;

    public Output<Integer> containerDiskInGb() {
        return this.containerDiskInGb;
    }
    @Export(name="containerRegistryAuthId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> containerRegistryAuthId;

    public Output<Optional<String>> containerRegistryAuthId() {
        return Codegen.optional(this.containerRegistryAuthId);
    }
    @Export(name="dockerArgs", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> dockerArgs;

    public Output<Optional<String>> dockerArgs() {
        return Codegen.optional(this.dockerArgs);
    }
    @Export(name="env", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output</* @Nullable */ Map<String,String>> env;

    public Output<Optional<Map<String,String>>> env() {
        return Codegen.optional(this.env);
    }
    @Export(name="imageName", refs={String.class}, tree="[0]")
    private Output<String> imageName;

    public Output<String> imageName() {
        return this.imageName;
    }
    @Export(name="isPublic", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> isPublic;

    public Output<Optional<Boolean>> isPublic() {
        return Codegen.optional(this.isPublic);
    }
    @Export(name="isServerless", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> isServerless;

    public Output<Optional<Boolean>> isServerless() {
        return Codegen.optional(this.isServerless);
    }
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    public Output<String> name() {
        return this.name;
    }
    @Export(name="ports", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> ports;

    public Output<Optional<String>> ports() {
        return Codegen.optional(this.ports);
    }
    @Export(name="readme", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> readme;

    public Output<Optional<String>> readme() {
        return Codegen.optional(this.readme);
    }
    @Export(name="startJupyter", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> startJupyter;

    public Output<Optional<Boolean>> startJupyter() {
        return Codegen.optional(this.startJupyter);
    }
    @Export(name="startScript", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> startScript;

    public Output<Optional<String>> startScript() {
        return Codegen.optional(this.startScript);
    }
    @Export(name="startSsh", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> startSsh;

    public Output<Optional<Boolean>> startSsh() {
        return Codegen.optional(this.startSsh);
    }
    @Export(name="templateId", refs={String.class}, tree="[0]")
    private Output<String> templateId;

    public Output<String> templateId() {
        return this.templateId;
    }
    @Export(name="volumeInGb", refs={Integer.class}, tree="[0]")
    private Output<Integer> volumeInGb;

    public Output<Integer> volumeInGb() {
        return this.volumeInGb;
    }
    @Export(name="volumeMountPath", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> volumeMountPath;

    public Output<Optional<String>> volumeMountPath() {
        return Codegen.optional(this.volumeMountPath);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Template(java.lang.String name) {
        this(name, TemplateArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Template(java.lang.String name, TemplateArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Template(java.lang.String name, TemplateArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("runpod:index:Template", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Template(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("runpod:index:Template", name, null, makeResourceOptions(options, id), false);
    }

    private static TemplateArgs makeArgs(TemplateArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? TemplateArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/runpod/pulumi-runpod")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Template get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Template(name, id, options);
    }
}
