// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface SavingsPlanArgs {
    /**
     * The length of the savings plan.
     */
    planLength?: pulumi.Input<string>;
    /**
     * The upfront cost for the savings plan.
     */
    upfrontCost?: pulumi.Input<number>;
}

export interface TemplatePortConfigArgs {
    name?: pulumi.Input<string>;
    port: pulumi.Input<string>;
}
