// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Endpoint extends pulumi.CustomResource {
    /**
     * Get an existing Endpoint resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Endpoint {
        return new Endpoint(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'runpod:index:Endpoint';

    /**
     * Returns true if the given object is an instance of Endpoint.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Endpoint {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Endpoint.__pulumiType;
    }

    /**
     * Comma-separated list of allowed CUDA versions.
     */
    public readonly allowedCudaVersions!: pulumi.Output<string | undefined>;
    /**
     * Whether to bind the endpoint to specific workers.
     */
    public readonly bindEndpoint!: pulumi.Output<boolean | undefined>;
    /**
     * The unique identifier of the endpoint.
     */
    public /*out*/ readonly endpointId!: pulumi.Output<string>;
    /**
     * Environment variables as key-value pairs.
     */
    public readonly env!: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * Maximum execution time in milliseconds before a request is terminated.
     */
    public readonly executionTimeoutMs!: pulumi.Output<number | undefined>;
    /**
     * The flash boot type.
     */
    public readonly flashBootType!: pulumi.Output<string | undefined>;
    /**
     * The flash environment ID.
     */
    public readonly flashEnvironmentId!: pulumi.Output<string | undefined>;
    /**
     * The number of GPUs per worker.
     */
    public readonly gpuCount!: pulumi.Output<number | undefined>;
    /**
     * The GPU type IDs to use (e.g. "AMPERE_16").
     */
    public readonly gpuIds!: pulumi.Output<string | undefined>;
    /**
     * The hub release ID for the endpoint.
     */
    public readonly hubReleaseId!: pulumi.Output<string | undefined>;
    /**
     * The number of seconds a worker can remain idle before being scaled down.
     */
    public readonly idleTimeout!: pulumi.Output<number | undefined>;
    /**
     * Specific instance IDs to use for workers.
     */
    public readonly instanceIds!: pulumi.Output<string[] | undefined>;
    /**
     * Comma-separated data center locations for worker deployment.
     */
    public readonly locations!: pulumi.Output<string | undefined>;
    /**
     * The minimum CUDA version required.
     */
    public readonly minCudaVersion!: pulumi.Output<string | undefined>;
    /**
     * The model name for the endpoint.
     */
    public readonly modelName!: pulumi.Output<string | undefined>;
    /**
     * Model references for the endpoint.
     */
    public readonly modelReferences!: pulumi.Output<string[] | undefined>;
    /**
     * A name for the endpoint.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * The network volume ID to attach to endpoint workers.
     */
    public readonly networkVolumeId!: pulumi.Output<string | undefined>;
    /**
     * The autoscaler type (e.g. "QUEUE_DELAY", "REQUEST_COUNT").
     */
    public readonly scalerType!: pulumi.Output<string | undefined>;
    /**
     * The autoscaler target value.
     */
    public readonly scalerValue!: pulumi.Output<number | undefined>;
    /**
     * The template ID to use for the endpoint workers.
     */
    public readonly templateId!: pulumi.Output<string | undefined>;
    /**
     * The endpoint type.
     */
    public readonly type!: pulumi.Output<string | undefined>;
    /**
     * The maximum number of workers to scale up to.
     */
    public readonly workersMax!: pulumi.Output<number | undefined>;
    /**
     * The minimum number of workers to keep running.
     */
    public readonly workersMin!: pulumi.Output<number | undefined>;

    /**
     * Create a Endpoint resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: EndpointArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.name === undefined) && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["allowedCudaVersions"] = args ? args.allowedCudaVersions : undefined;
            resourceInputs["bindEndpoint"] = args ? args.bindEndpoint : undefined;
            resourceInputs["env"] = args ? args.env : undefined;
            resourceInputs["executionTimeoutMs"] = args ? args.executionTimeoutMs : undefined;
            resourceInputs["flashBootType"] = args ? args.flashBootType : undefined;
            resourceInputs["flashEnvironmentId"] = args ? args.flashEnvironmentId : undefined;
            resourceInputs["gpuCount"] = args ? args.gpuCount : undefined;
            resourceInputs["gpuIds"] = args ? args.gpuIds : undefined;
            resourceInputs["hubReleaseId"] = args ? args.hubReleaseId : undefined;
            resourceInputs["idleTimeout"] = args ? args.idleTimeout : undefined;
            resourceInputs["instanceIds"] = args ? args.instanceIds : undefined;
            resourceInputs["locations"] = args ? args.locations : undefined;
            resourceInputs["minCudaVersion"] = args ? args.minCudaVersion : undefined;
            resourceInputs["modelName"] = args ? args.modelName : undefined;
            resourceInputs["modelReferences"] = args ? args.modelReferences : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["networkVolumeId"] = args ? args.networkVolumeId : undefined;
            resourceInputs["scalerType"] = args ? args.scalerType : undefined;
            resourceInputs["scalerValue"] = args ? args.scalerValue : undefined;
            resourceInputs["templateId"] = args ? args.templateId : undefined;
            resourceInputs["type"] = args ? args.type : undefined;
            resourceInputs["workersMax"] = args ? args.workersMax : undefined;
            resourceInputs["workersMin"] = args ? args.workersMin : undefined;
            resourceInputs["endpointId"] = undefined /*out*/;
        } else {
            resourceInputs["allowedCudaVersions"] = undefined /*out*/;
            resourceInputs["bindEndpoint"] = undefined /*out*/;
            resourceInputs["endpointId"] = undefined /*out*/;
            resourceInputs["env"] = undefined /*out*/;
            resourceInputs["executionTimeoutMs"] = undefined /*out*/;
            resourceInputs["flashBootType"] = undefined /*out*/;
            resourceInputs["flashEnvironmentId"] = undefined /*out*/;
            resourceInputs["gpuCount"] = undefined /*out*/;
            resourceInputs["gpuIds"] = undefined /*out*/;
            resourceInputs["hubReleaseId"] = undefined /*out*/;
            resourceInputs["idleTimeout"] = undefined /*out*/;
            resourceInputs["instanceIds"] = undefined /*out*/;
            resourceInputs["locations"] = undefined /*out*/;
            resourceInputs["minCudaVersion"] = undefined /*out*/;
            resourceInputs["modelName"] = undefined /*out*/;
            resourceInputs["modelReferences"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["networkVolumeId"] = undefined /*out*/;
            resourceInputs["scalerType"] = undefined /*out*/;
            resourceInputs["scalerValue"] = undefined /*out*/;
            resourceInputs["templateId"] = undefined /*out*/;
            resourceInputs["type"] = undefined /*out*/;
            resourceInputs["workersMax"] = undefined /*out*/;
            resourceInputs["workersMin"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Endpoint.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Endpoint resource.
 */
export interface EndpointArgs {
    /**
     * Comma-separated list of allowed CUDA versions.
     */
    allowedCudaVersions?: pulumi.Input<string>;
    /**
     * Whether to bind the endpoint to specific workers.
     */
    bindEndpoint?: pulumi.Input<boolean>;
    /**
     * Environment variables as key-value pairs.
     */
    env?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Maximum execution time in milliseconds before a request is terminated.
     */
    executionTimeoutMs?: pulumi.Input<number>;
    /**
     * The flash boot type.
     */
    flashBootType?: pulumi.Input<string>;
    /**
     * The flash environment ID.
     */
    flashEnvironmentId?: pulumi.Input<string>;
    /**
     * The number of GPUs per worker.
     */
    gpuCount?: pulumi.Input<number>;
    /**
     * The GPU type IDs to use (e.g. "AMPERE_16").
     */
    gpuIds?: pulumi.Input<string>;
    /**
     * The hub release ID for the endpoint.
     */
    hubReleaseId?: pulumi.Input<string>;
    /**
     * The number of seconds a worker can remain idle before being scaled down.
     */
    idleTimeout?: pulumi.Input<number>;
    /**
     * Specific instance IDs to use for workers.
     */
    instanceIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Comma-separated data center locations for worker deployment.
     */
    locations?: pulumi.Input<string>;
    /**
     * The minimum CUDA version required.
     */
    minCudaVersion?: pulumi.Input<string>;
    /**
     * The model name for the endpoint.
     */
    modelName?: pulumi.Input<string>;
    /**
     * Model references for the endpoint.
     */
    modelReferences?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * A name for the endpoint.
     */
    name: pulumi.Input<string>;
    /**
     * The network volume ID to attach to endpoint workers.
     */
    networkVolumeId?: pulumi.Input<string>;
    /**
     * The autoscaler type (e.g. "QUEUE_DELAY", "REQUEST_COUNT").
     */
    scalerType?: pulumi.Input<string>;
    /**
     * The autoscaler target value.
     */
    scalerValue?: pulumi.Input<number>;
    /**
     * The template ID to use for the endpoint workers.
     */
    templateId?: pulumi.Input<string>;
    /**
     * The endpoint type.
     */
    type?: pulumi.Input<string>;
    /**
     * The maximum number of workers to scale up to.
     */
    workersMax?: pulumi.Input<number>;
    /**
     * The minimum number of workers to keep running.
     */
    workersMin?: pulumi.Input<number>;
}
