// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getCPUFlavors(args?: GetCPUFlavorsArgs, opts?: pulumi.InvokeOptions): Promise<GetCPUFlavorsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("runpod:index:getCPUFlavors", {
        "isSls": args.isSls,
        "slsOnly": args.slsOnly,
    }, opts);
}

export interface GetCPUFlavorsArgs {
    /**
     * Filter by serverless eligibility.
     */
    isSls?: boolean;
    /**
     * When true, return only serverless-eligible CPU flavors.
     */
    slsOnly?: boolean;
}

export interface GetCPUFlavorsResult {
    /**
     * The list of available CPU instance flavors.
     */
    readonly cpuFlavors: outputs.CPUFlavorOutput[];
}
export function getCPUFlavorsOutput(args?: GetCPUFlavorsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetCPUFlavorsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("runpod:index:getCPUFlavors", {
        "isSls": args.isSls,
        "slsOnly": args.slsOnly,
    }, opts);
}

export interface GetCPUFlavorsOutputArgs {
    /**
     * Filter by serverless eligibility.
     */
    isSls?: pulumi.Input<boolean>;
    /**
     * When true, return only serverless-eligible CPU flavors.
     */
    slsOnly?: pulumi.Input<boolean>;
}
