// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class NetworkVolume extends pulumi.CustomResource {
    /**
     * Get an existing NetworkVolume resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): NetworkVolume {
        return new NetworkVolume(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'runpod:index:NetworkVolume';

    /**
     * Returns true if the given object is an instance of NetworkVolume.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is NetworkVolume {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === NetworkVolume.__pulumiType;
    }

    public readonly dataCenterId!: pulumi.Output<string>;
    public readonly isNextGenStorage!: pulumi.Output<boolean | undefined>;
    public readonly name!: pulumi.Output<string>;
    public /*out*/ readonly networkVolumeId!: pulumi.Output<string>;
    public readonly size!: pulumi.Output<number>;

    /**
     * Create a NetworkVolume resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: NetworkVolumeArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.dataCenterId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'dataCenterId'");
            }
            if ((!args || args.name === undefined) && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if ((!args || args.size === undefined) && !opts.urn) {
                throw new Error("Missing required property 'size'");
            }
            resourceInputs["dataCenterId"] = args ? args.dataCenterId : undefined;
            resourceInputs["isNextGenStorage"] = args ? args.isNextGenStorage : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["size"] = args ? args.size : undefined;
            resourceInputs["networkVolumeId"] = undefined /*out*/;
        } else {
            resourceInputs["dataCenterId"] = undefined /*out*/;
            resourceInputs["isNextGenStorage"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["networkVolumeId"] = undefined /*out*/;
            resourceInputs["size"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(NetworkVolume.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a NetworkVolume resource.
 */
export interface NetworkVolumeArgs {
    dataCenterId: pulumi.Input<string>;
    isNextGenStorage?: pulumi.Input<boolean>;
    name: pulumi.Input<string>;
    size: pulumi.Input<number>;
}
